INSERT INTO hive_table
SELECT
SESSION_ID,
APP_NO,
CUST_ID,
BUSINESS_TYPE_CD,
BUSINESS_TYPE_NAME,
CUST_SOURCE,
CHANNEL_SOURCE,
APPLY_TIME
--TO_TIMESTAMP(FROM_UNIXTIME(APPLY_TIME/1000,'yyyy-MM-dd HH:mm:ss')) AS APPLY_TIME
FROM kafka_apply_info_106
;