-- source表
CREATE TABLE source_table_1 (
      event_id STRING COMMIT '事件编号',
      cd_org_cd STRING COMMIT '信用卡ORG代码',
      acct_num STRING COMMIT '账号',
      acct_modifier_num STRING COMMIT '账号修饰符',
      cust_id STRING COMMIT '客户号',
      card_num STRING COMMIT '卡号',
      card_seq_num STRING COMMIT '卡序号',
      logo_cd STRING COMMIT 'LOGO代码',
      subbranch_id STRING COMMIT '账户所属支行',
      txn_ref_num STRING COMMIT '金融交易参考号',
      txn_type_cd STRING COMMIT '金融交易类型代码',
      txn_dt STRING COMMIT '交易日期',
      batch_dt STRING COMMIT '批量日期',
      posting_dt STRING COMMIT '入账日期',
      cd_plan_num STRING COMMIT '信用计划号',
      txn_cd STRING COMMIT '交易代码',
      logic_module_cd STRING COMMIT '逻辑模块代码',
      txn_amt STRING COMMIT '交易金额',
      rmb_txn_amt STRING COMMIT '交易金额折人民币',
      auth_num    STRING    COMMIT '授权号',
      lty_pgm_num    STRING    COMMIT '积分计划编号',
      txn_pts_nbr    DECIMAL(18,2)    COMMIT '事件积分',
      external_txn_id    STRING    COMMIT '外部交易ID',
      mcc_cd    STRING    COMMIT 'MCC代码',
      equip_card_num    STRING    COMMIT '设备卡号',
      equip_card_type_cd    STRING    COMMIT '设备卡类型代码',
      merchant_country_cd    STRING    COMMIT '商户国家代码',
      merchant_id    STRING    COMMIT '商户编号',
      txn_desc    STRING    COMMIT '交易描述',
      txn_terminal_num    STRING    COMMIT '交易终端编号',
      gl_src_cd    STRING    COMMIT '总账来源代码',
      txn_src_cd    STRING    COMMIT '交易来源代码',
      txn_src_type_cd    STRING    COMMIT '交易来源分类代码',
      currency_conv_type_cd    STRING    COMMIT '货币转换类型代码',
      ec_txn_type_cd    STRING    COMMIT '电子商务交易类型代码',
      curr_conv_charge_mode_cd    STRING    COMMIT '货币转换收费方式代码',
      use_method_cd    STRING    COMMIT '使用方式代码',
      deal_bank_org_id    STRING    COMMIT '受理行机构编号',
      union_pay_sys_trace_num    STRING    COMMIT '银联系统跟踪号',
      spec_fee_type    STRING    COMMIT '特殊计费类型',
      spec_fee_level    STRING    COMMIT '特殊计费档次',
      txn_tm    STRING    COMMIT '交易时间',
      pbc_remittance_biz_id    STRING    COMMIT '人行大小额汇款业务编号',
      extend_merc_name    STRING    COMMIT '扩展商户名称',
      level2_merc_name    STRING    COMMIT '二级商户名称',
      biz_product_type_cd    STRING    COMMIT '业务产品类型代码',
      payer_name    STRING    COMMIT '付款方姓名',
      pay_acct_num    STRING    COMMIT '付款账号',
      payment_remark    STRING    COMMIT '代付附言',
      pbcc_nc_txn_seq_num    STRING    COMMIT '人行网联交易流水号',
      nc_instalment_fee_type_cd    STRING    COMMIT '网联分期手续费收取类型代码',
      nc_instalment_prod_cd    STRING COMMIT '网联分期分期产品代码',
      acqr_bank_id    STRING    COMMIT '收单行行号',
      pay_acct_type_cd    STRING    COMMIT '付款账号类型代码',
      app_service_id    STRING    COMMIT '应用服务方ID',
      org_name    STRING    COMMIT '机构名称',
      biz_desc    STRING    COMMIT '业务描述',
      new_borrow_flage    INT    COMMIT '借贷标记',
      new_account_chinessname STRING  COMMIT '账户中文名',
      match_auth_txn_ind    STRING    COMMIT '匹配到授权交易标志',
      data_dt    STRING    COMMIT '数据日期'
      et AS TO_TIMESTAMP(FROM_UNIXTIME(cast(data_dt as bigint)/1000)),
      WATERMARK FOR et AS et - INTERVAL '5' SECOND
    )
    WITH (
      'connector' = 'kafka',
      'topic' = 'source_table_1',
      'properties.group.id'='dev_flink',
      'properties.zookeeper.connect'='10.1.30.6:2181',
      'properties.bootstrap.servers' = '10.1.30.8:9092',
      'format' = 'json',
      'scan.startup.mode' = 'latest-offset'
      );
-- 结果表
create table sink_table_1(
		xiaofei_01 INTEGER COMMIT '最近1天&Transtype.交易笔数',
		xiaofei_02 decimal COMMIT '最近1天&Transtype.交易金额',
		xiaofei_03 decimal COMMIT '最近1天&Transtype.最大交易金额',
		xiaofei_04 INTEGER COMMIT '最近1天&Transtype.发生交易天数',
		xiaofei_05 INTEGER COMMIT '最近1天的日均&Transtype.交易笔数',
		xiaofei_06 decimal COMMIT '最近1天的日均&Transtype.交易金额',
		xiaofei_07 FLOAT COMMIT '最近1天的&Transtype.交易金额占授信额度比例',
		xiaofei_08 FLOAT COMMIT '最近1天与最近1天内的日均&Transtype.交易笔数的比例',
		xiaofei_09 FLOAT COMMIT '最近1天与最近1天内的日均&Transtype.交易金额的比例',
		xiaofei_11 INTEGER COMMIT '最近3天&Transtype.交易笔数',
		xiaofei_12 DECIMAL(18,2) COMMIT '最近3天&Transtype.交易金额',
		xiaofei_13 DECIMAL(18,2) COMMIT '最近3天&Transtype.最大交易金额',
		xiaofei_14 INTEGER COMMIT '最近3天&Transtype.发生交易天数',
		xiaofei_15 INTEGER COMMIT '最近3天的日均&Transtype.交易笔数',
		xiaofei_16 DECIMAL(18,2) COMMIT '最近3天的日均&Transtype.交易金额',
		xiaofei_17 FLOAT COMMIT '最近3天的&Transtype.交易金额占授信额度比例',
		xiaofei_18 FLOAT COMMIT '最近3天与最近3天内的日均&Transtype.交易笔数的比例',
		xiaofei_19 FLOAT COMMIT '最近3天与最近3天内的日均&Transtype.交易金额的比例',
		xiaofei_20 STRING COMMIT '是否最近3天连续&Transtype.',
		xiaofei_21 STRING COMMIT '是否最近3天连续&Transtype.金额大于5万',
		xiaofei_22 STRING COMMIT '是否最近3天连续&Transtype.金额大于10万',
		xiaofei_23 STRING COMMIT '是否最近3天连续&Transtype.金额大于25万',
		xiaofei_24 STRING COMMIT '是否最近3天连续&Transtype.金额大于50万',
		bangong_01 INTEGER COMMIT '最近1天&Transtype.交易笔数',
		bangong_02 decimal COMMIT '最近1天&Transtype.交易金额',
		bangong_03 decimal COMMIT '最近1天&Transtype.最大交易金额',
		bangong_04 INTEGER COMMIT '最近1天&Transtype.发生交易天数',
		bangong_05 INTEGER COMMIT '最近1天的日均&Transtype.交易笔数',
		bangong_06 decimal COMMIT '最近1天的日均&Transtype.交易金额',
		bangong_07 FLOAT COMMIT '最近1天的&Transtype.交易金额占授信额度比例',
		bangong_08 FLOAT COMMIT '最近1天与最近1天内的日均&Transtype.交易笔数的比例',
		bangong_09 FLOAT COMMIT '最近1天与最近1天内的日均&Transtype.交易金额的比例',
		bangong_11 INTEGER COMMIT '最近3天&Transtype.交易笔数',
		bangong_12 DECIMAL(18,2) COMMIT '最近3天&Transtype.交易金额',
		bangong_13 DECIMAL(18,2) COMMIT '最近3天&Transtype.最大交易金额',
		bangong_14 INTEGER COMMIT '最近3天&Transtype.发生交易天数',
		bangong_15 INTEGER COMMIT '最近3天的日均&Transtype.交易笔数',
		bangong_16 DECIMAL(18,2) COMMIT '最近3天的日均&Transtype.交易金额',
		bangong_17 FLOAT COMMIT '最近3天的&Transtype.交易金额占授信额度比例',
		bangong_18 FLOAT COMMIT '最近3天与最近3天内的日均&Transtype.交易笔数的比例',
		bangong_19 FLOAT COMMIT '最近3天与最近3天内的日均&Transtype.交易金额的比例',
		bangong_20 STRING COMMIT '是否最近3天连续&Transtype.',
		bangong_21 STRING COMMIT '是否最近3天连续&Transtype.金额大于5万',
		bangong_22 STRING COMMIT '是否最近3天连续&Transtype.金额大于10万',
		bangong_23 STRING COMMIT '是否最近3天连续&Transtype.金额大于25万',
		bangong_24 STRING COMMIT '是否最近3天连续&Transtype.金额大于50万',
		xinzi_01 INTEGER COMMIT '最近1天&Transtype.交易笔数',
		xinzi_02 decimal COMMIT '最近1天&Transtype.交易金额',
		xinzi_03 decimal COMMIT '最近1天&Transtype.最大交易金额',
		xinzi_04 INTEGER COMMIT '最近1天&Transtype.发生交易天数',
		xinzi_05 INTEGER COMMIT '最近1天的日均&Transtype.交易笔数',
		xinzi_06 decimal COMMIT '最近1天的日均&Transtype.交易金额',
		xinzi_07 FLOAT COMMIT '最近1天的&Transtype.交易金额占授信额度比例',
		xinzi_08 FLOAT COMMIT '最近1天与最近1天内的日均&Transtype.交易笔数的比例',
		xinzi_09 FLOAT COMMIT '最近1天与最近1天内的日均&Transtype.交易金额的比例',
		xinzi_11 INTEGER COMMIT '最近3天&Transtype.交易笔数',
		xinzi_12 DECIMAL(18,2) COMMIT '最近3天&Transtype.交易金额',
		xinzi_13 DECIMAL(18,2) COMMIT '最近3天&Transtype.最大交易金额',
		xinzi_14 INTEGER COMMIT '最近3天&Transtype.发生交易天数',
		xinzi_15 INTEGER COMMIT '最近3天的日均&Transtype.交易笔数',
		xinzi_16 DECIMAL(18,2) COMMIT '最近3天的日均&Transtype.交易金额',
		xinzi_17 FLOAT COMMIT '最近3天的&Transtype.交易金额占授信额度比例',
		xinzi_18 FLOAT COMMIT '最近3天与最近3天内的日均&Transtype.交易笔数的比例',
		xinzi_19 FLOAT COMMIT '最近3天与最近3天内的日均&Transtype.交易金额的比例',
		xinzi_20 STRING COMMIT '是否最近3天连续&Transtype.',
		xinzi_21 STRING COMMIT '是否最近3天连续&Transtype.金额大于5万',
		xinzi_22 STRING COMMIT '是否最近3天连续&Transtype.金额大于10万',
		xinzi_23 STRING COMMIT '是否最近3天连续&Transtype.金额大于25万',
		xinzi_24 STRING COMMIT '是否最近3天连续&Transtype.金额大于50万',
		baoxian_01 INTEGER COMMIT '最近1天&Transtype.交易笔数',
		baoxian_02 decimal COMMIT '最近1天&Transtype.交易金额',
		baoxian_03 decimal COMMIT '最近1天&Transtype.最大交易金额',
		baoxian_04 INTEGER COMMIT '最近1天&Transtype.发生交易天数',
		baoxian_05 INTEGER COMMIT '最近1天的日均&Transtype.交易笔数',
		baoxian_06 decimal COMMIT '最近1天的日均&Transtype.交易金额',
		baoxian_07 FLOAT COMMIT '最近1天的&Transtype.交易金额占授信额度比例',
		baoxian_08 FLOAT COMMIT '最近1天与最近1天内的日均&Transtype.交易笔数的比例',
		baoxian_09 FLOAT COMMIT '最近1天与最近1天内的日均&Transtype.交易金额的比例',
		baoxian_11 INTEGER COMMIT '最近3天&Transtype.交易笔数',
		baoxian_12 DECIMAL(18,2) COMMIT '最近3天&Transtype.交易金额',
		baoxian_13 DECIMAL(18,2) COMMIT '最近3天&Transtype.最大交易金额',
		baoxian_14 INTEGER COMMIT '最近3天&Transtype.发生交易天数',
		baoxian_15 INTEGER COMMIT '最近3天的日均&Transtype.交易笔数',
		baoxian_16 DECIMAL(18,2) COMMIT '最近3天的日均&Transtype.交易金额',
		baoxian_17 FLOAT COMMIT '最近3天的&Transtype.交易金额占授信额度比例',
		baoxian_18 FLOAT COMMIT '最近3天与最近3天内的日均&Transtype.交易笔数的比例',
		baoxian_19 FLOAT COMMIT '最近3天与最近3天内的日均&Transtype.交易金额的比例',
		baoxian_20 STRING COMMIT '是否最近3天连续&Transtype.',
		baoxian_21 STRING COMMIT '是否最近3天连续&Transtype.金额大于5万',
		baoxian_22 STRING COMMIT '是否最近3天连续&Transtype.金额大于10万',
		baoxian_23 STRING COMMIT '是否最近3天连续&Transtype.金额大于25万',
		baoxian_24 STRING COMMIT '是否最近3天连续&Transtype.金额大于50万',
		touzi_01 INTEGER COMMIT '最近1天&Transtype.交易笔数',
		touzi_02 decimal COMMIT '最近1天&Transtype.交易金额',
		touzi_03 decimal COMMIT '最近1天&Transtype.最大交易金额',
		touzi_04 INTEGER COMMIT '最近1天&Transtype.发生交易天数',
		touzi_05 INTEGER COMMIT '最近1天的日均&Transtype.交易笔数',
		touzi_06 decimal COMMIT '最近1天的日均&Transtype.交易金额',
		touzi_07 FLOAT COMMIT '最近1天的&Transtype.交易金额占授信额度比例',
		touzi_08 FLOAT COMMIT '最近1天与最近1天内的日均&Transtype.交易笔数的比例',
		touzi_09 FLOAT COMMIT '最近1天与最近1天内的日均&Transtype.交易金额的比例',
		touzi_11 INTEGER COMMIT '最近3天&Transtype.交易笔数',
		touzi_12 DECIMAL(18,2) COMMIT '最近3天&Transtype.交易金额',
		touzi_13 DECIMAL(18,2) COMMIT '最近3天&Transtype.最大交易金额',
		touzi_14 INTEGER COMMIT '最近3天&Transtype.发生交易天数',
		touzi_15 INTEGER COMMIT '最近3天的日均&Transtype.交易笔数',
		touzi_16 DECIMAL(18,2) COMMIT '最近3天的日均&Transtype.交易金额',
		touzi_17 FLOAT COMMIT '最近3天的&Transtype.交易金额占授信额度比例',
		touzi_18 FLOAT COMMIT '最近3天与最近3天内的日均&Transtype.交易笔数的比例',
		touzi_19 FLOAT COMMIT '最近3天与最近3天内的日均&Transtype.交易金额的比例',
		touzi_20 STRING COMMIT '是否最近3天连续&Transtype.',
		touzi_21 STRING COMMIT '是否最近3天连续&Transtype.金额大于5万',
		touzi_22 STRING COMMIT '是否最近3天连续&Transtype.金额大于10万',
		touzi_23 STRING COMMIT '是否最近3天连续&Transtype.金额大于25万',
		touzi_24 STRING COMMIT '是否最近3天连续&Transtype.金额大于50万',
		rongzi_01 INTEGER COMMIT '最近1天&Transtype.交易笔数',
		rongzi_02 decimal COMMIT '最近1天&Transtype.交易金额',
		rongzi_03 decimal COMMIT '最近1天&Transtype.最大交易金额',
		rongzi_04 INTEGER COMMIT '最近1天&Transtype.发生交易天数',
		rongzi_05 INTEGER COMMIT '最近1天的日均&Transtype.交易笔数',
		rongzi_06 decimal COMMIT '最近1天的日均&Transtype.交易金额',
		rongzi_07 FLOAT COMMIT '最近1天的&Transtype.交易金额占授信额度比例',
		rongzi_08 FLOAT COMMIT '最近1天与最近1天内的日均&Transtype.交易笔数的比例',
		rongzi_09 FLOAT COMMIT '最近1天与最近1天内的日均&Transtype.交易金额的比例',
		rongzi_11 INTEGER COMMIT '最近3天&Transtype.交易笔数',
		rongzi_12 DECIMAL(18,2) COMMIT '最近3天&Transtype.交易金额',
		rongzi_13 DECIMAL(18,2) COMMIT '最近3天&Transtype.最大交易金额',
		rongzi_14 INTEGER COMMIT '最近3天&Transtype.发生交易天数',
		rongzi_15 INTEGER COMMIT '最近3天的日均&Transtype.交易笔数',
		rongzi_16 DECIMAL(18,2) COMMIT '最近3天的日均&Transtype.交易金额',
		rongzi_17 FLOAT COMMIT '最近3天的&Transtype.交易金额占授信额度比例',
		rongzi_18 FLOAT COMMIT '最近3天与最近3天内的日均&Transtype.交易笔数的比例',
		rongzi_19 FLOAT COMMIT '最近3天与最近3天内的日均&Transtype.交易金额的比例',
		rongzi_20 STRING COMMIT '是否最近3天连续&Transtype.',
		rongzi_21 STRING COMMIT '是否最近3天连续&Transtype.金额大于5万',
		rongzi_22 STRING COMMIT '是否最近3天连续&Transtype.金额大于10万',
		rongzi_23 STRING COMMIT '是否最近3天连续&Transtype.金额大于25万',
		rongzi_24 STRING COMMIT '是否最近3天连续&Transtype.金额大于50万',
		zhuanzhang_01 INTEGER COMMIT '最近1天&Transtype.交易笔数',
		zhuanzhang_02 decimal COMMIT '最近1天&Transtype.交易金额',
		zhuanzhang_03 decimal COMMIT '最近1天&Transtype.最大交易金额',
		zhuanzhang_04 INTEGER COMMIT '最近1天&Transtype.发生交易天数',
		zhuanzhang_05 INTEGER COMMIT '最近1天的日均&Transtype.交易笔数',
		zhuanzhang_06 decimal COMMIT '最近1天的日均&Transtype.交易金额',
		zhuanzhang_07 FLOAT COMMIT '最近1天的&Transtype.交易金额占授信额度比例',
		zhuanzhang_08 FLOAT COMMIT '最近1天与最近1天内的日均&Transtype.交易笔数的比例',
		zhuanzhang_09 FLOAT COMMIT '最近1天与最近1天内的日均&Transtype.交易金额的比例',
		zhuanzhang_11 INTEGER COMMIT '最近3天&Transtype.交易笔数',
		zhuanzhang_12 DECIMAL(18,2) COMMIT '最近3天&Transtype.交易金额',
		zhuanzhang_13 DECIMAL(18,2) COMMIT '最近3天&Transtype.最大交易金额',
		zhuanzhang_14 INTEGER COMMIT '最近3天&Transtype.发生交易天数',
		zhuanzhang_15 INTEGER COMMIT '最近3天的日均&Transtype.交易笔数',
		zhuanzhang_16 DECIMAL(18,2) COMMIT '最近3天的日均&Transtype.交易金额',
		zhuanzhang_17 FLOAT COMMIT '最近3天的&Transtype.交易金额占授信额度比例',
		zhuanzhang_18 FLOAT COMMIT '最近3天与最近3天内的日均&Transtype.交易笔数的比例',
		zhuanzhang_19 FLOAT COMMIT '最近3天与最近3天内的日均&Transtype.交易金额的比例',
		zhuanzhang_20 STRING COMMIT '是否最近3天连续&Transtype.',
		zhuanzhang_21 STRING COMMIT '是否最近3天连续&Transtype.金额大于5万',
		zhuanzhang_22 STRING COMMIT '是否最近3天连续&Transtype.金额大于10万',
		zhuanzhang_23 STRING COMMIT '是否最近3天连续&Transtype.金额大于25万',
		zhuanzhang_24 STRING COMMIT '是否最近3天连续&Transtype.金额大于50万',
		cunqu_01 INTEGER COMMIT '最近1天&Transtype.交易笔数',
		cunqu_02 decimal COMMIT '最近1天&Transtype.交易金额',
		cunqu_03 decimal COMMIT '最近1天&Transtype.最大交易金额',
		cunqu_04 INTEGER COMMIT '最近1天&Transtype.发生交易天数',
		cunqu_05 INTEGER COMMIT '最近1天的日均&Transtype.交易笔数',
		cunqu_06 decimal COMMIT '最近1天的日均&Transtype.交易金额',
		cunqu_07 FLOAT COMMIT '最近1天的&Transtype.交易金额占授信额度比例',
		cunqu_08 FLOAT COMMIT '最近1天与最近1天内的日均&Transtype.交易笔数的比例',
		cunqu_09 FLOAT COMMIT '最近1天与最近1天内的日均&Transtype.交易金额的比例',
		cunqu_11 INTEGER COMMIT '最近3天&Transtype.交易笔数',
		cunqu_12 DECIMAL(18,2) COMMIT '最近3天&Transtype.交易金额',
		cunqu_13 DECIMAL(18,2) COMMIT '最近3天&Transtype.最大交易金额',
		cunqu_14 INTEGER COMMIT '最近3天&Transtype.发生交易天数',
		cunqu_15 INTEGER COMMIT '最近3天的日均&Transtype.交易笔数',
		cunqu_16 DECIMAL(18,2) COMMIT '最近3天的日均&Transtype.交易金额',
		cunqu_17 FLOAT COMMIT '最近3天的&Transtype.交易金额占授信额度比例',
		cunqu_18 FLOAT COMMIT '最近3天与最近3天内的日均&Transtype.交易笔数的比例',
		cunqu_19 FLOAT COMMIT '最近3天与最近3天内的日均&Transtype.交易金额的比例',
		cunqu_20 STRING COMMIT '是否最近3天连续&Transtype.',
		cunqu_21 STRING COMMIT '是否最近3天连续&Transtype.金额大于5万',
		cunqu_22 STRING COMMIT '是否最近3天连续&Transtype.金额大于10万',
		cunqu_23 STRING COMMIT '是否最近3天连续&Transtype.金额大于25万',
		cunqu_24 STRING COMMIT '是否最近3天连续&Transtype.金额大于50万',
		other_01 INTEGER COMMIT '最近1天&Transtype.交易笔数',
		other_02 decimal COMMIT '最近1天&Transtype.交易金额',
		other_03 decimal COMMIT '最近1天&Transtype.最大交易金额',
		other_04 INTEGER COMMIT '最近1天&Transtype.发生交易天数',
		other_05 INTEGER COMMIT '最近1天的日均&Transtype.交易笔数',
		other_06 decimal COMMIT '最近1天的日均&Transtype.交易金额',
		other_07 FLOAT COMMIT '最近1天的&Transtype.交易金额占授信额度比例',
		other_08 FLOAT COMMIT '最近1天与最近1天内的日均&Transtype.交易笔数的比例',
		other_09 FLOAT COMMIT '最近1天与最近1天内的日均&Transtype.交易金额的比例',
		other_11 INTEGER COMMIT '最近3天&Transtype.交易笔数',
		other_12 DECIMAL(18,2) COMMIT '最近3天&Transtype.交易金额',
		other_13 DECIMAL(18,2) COMMIT '最近3天&Transtype.最大交易金额',
		other_14 INTEGER COMMIT '最近3天&Transtype.发生交易天数',
		other_15 INTEGER COMMIT '最近3天的日均&Transtype.交易笔数',
		other_16 DECIMAL(18,2) COMMIT '最近3天的日均&Transtype.交易金额',
		other_17 FLOAT COMMIT '最近3天的&Transtype.交易金额占授信额度比例',
		other_18 FLOAT COMMIT '最近3天与最近3天内的日均&Transtype.交易笔数的比例',
		other_19 FLOAT COMMIT '最近3天与最近3天内的日均&Transtype.交易金额的比例',
		other_20 STRING COMMIT '是否最近3天连续&Transtype.',
		other_21 STRING COMMIT '是否最近3天连续&Transtype.金额大于5万',
		other_22 STRING COMMIT '是否最近3天连续&Transtype.金额大于10万',
		other_23 STRING COMMIT '是否最近3天连续&Transtype.金额大于25万',
		other_24 STRING COMMIT '是否最近3天连续&Transtype.金额大于50万')
		WITH (
      'connector' = 'kafka',
      'topic' = 'qinghua_sink_table',
      'properties.group.id'='dev_flink',
      'properties.zookeeper.connect'='10.1.30.6:2181',
      'properties.bootstrap.servers' = '10.1.30.8:9092',
      'format' = 'json',
      'scan.startup.mode' = 'latest-offset'
      );

-- 注册函数
create function my_function as 'com.cebbank.airisk.flink.udfs.PreviousValueAggFunction$LongPreviousValueAggFunction';

-- 这个view的格式为
--  event_id       transtype        交易金额
create view mid_data_table_1 as
select
      event_id,
	  case
	  when my_function(payer_name,acct_num,currency_conv_type_cd,txn_cd,txn_amt,new_borrow_flage,biz_product_type_cd,txn_desc,new_account_chinessname) like '1%' then 'xiaofei'
	  when my_function(payer_name,acct_num,currency_conv_type_cd,txn_cd,txn_amt,new_borrow_flage,biz_product_type_cd,txn_desc,new_account_chinessname) like '2%' then 'bangong'
	  when my_function(payer_name,acct_num,currency_conv_type_cd,txn_cd,txn_amt,new_borrow_flage,biz_product_type_cd,txn_desc,new_account_chinessname) like '3%' then 'xinzi'
	  when my_function(payer_name,acct_num,currency_conv_type_cd,txn_cd,txn_amt,new_borrow_flage,biz_product_type_cd,txn_desc,new_account_chinessname) like '4%' then 'baoxian'
	  when my_function(payer_name,acct_num,currency_conv_type_cd,txn_cd,txn_amt,new_borrow_flage,biz_product_type_cd,txn_desc,new_account_chinessname) like '5%' then 'touzi'
	  when my_function(payer_name,acct_num,currency_conv_type_cd,txn_cd,txn_amt,new_borrow_flage,biz_product_type_cd,txn_desc,new_account_chinessname) like '6%' then 'rongzi'
	  when my_function(payer_name,acct_num,currency_conv_type_cd,txn_cd,txn_amt,new_borrow_flage,biz_product_type_cd,txn_desc,new_account_chinessname) like '7%' then 'zhuanzhang'
	  when my_function(payer_name,acct_num,currency_conv_type_cd,txn_cd,txn_amt,new_borrow_flage,biz_product_type_cd,txn_desc,new_account_chinessname) like '8%' then 'cunqu'
	  when my_function(payer_name,acct_num,currency_conv_type_cd,txn_cd,txn_amt,new_borrow_flage,biz_product_type_cd,txn_desc,new_account_chinessname) like '9%' then 'other'
	  end as transtype,
	  cast(txn_amt as decimal ) as amount,
	  cast(txn_cd as decimal ) as cd,
	  txn_dt as txn_dt,
	   et
	  from source_table_1;

-- todo 创建一个中间视图 4个字段
-- 9种类型的字段
--  et      xiaofei_amount      xiaofei_cd      xiaofei_txn_dt      ...........
create view every_type_info_table as
select
    et,
    if(mid_data_table_1.transtype='xiaofei',mid_data_table_1.amount,0) xiaofei_amount,
    if(mid_data_table_1.transtype='xiaofei',mid_data_table_1.cd,0) xiaofei_cd,
    if(mid_data_table_1.transtype='xiaofei',mid_data_table_1.txn_dt,0) xiaofei_txn_dt,
    if(mid_data_table_1.transtype='bangong',mid_data_table_1.amount,0) bangong_amount,
    if(mid_data_table_1.transtype='bangong',mid_data_table_1.cd,0) bangong_cd,
    if(mid_data_table_1.transtype='bangong',mid_data_table_1.ctxn_dt,0) bangong_txn_dt,
    if(mid_data_table_1.transtype='xinzi',mid_data_table_1.amount,0) xinzi_amount,
    if(mid_data_table_1.transtype='xinzi',mid_data_table_1.cd,0) xinzi_cd,
    if(mid_data_table_1.transtype='xinzi',mid_data_table_1.txn_dt,0) xinzi_txn_dt,
    if(mid_data_table_1.transtype='baoxian',mid_data_table_1.amount,0) baoxian_amount,
    if(mid_data_table_1.transtype='baoxian',mid_data_table_1.cd,0) baoxian_cd,
    if(mid_data_table_1.transtype='baoxian',mid_data_table_1.txn_dt,0) baoxian_txn_dt,
    if(mid_data_table_1.transtype='touzi',mid_data_table_1.amount,0) touzi_amount,
    if(mid_data_table_1.transtype='touzi',mid_data_table_1.cd,0) touzi_cd,
    if(mid_data_table_1.transtype='touzi',mid_data_table_1.txn_dt,0) touzi_txn_dt,
    if(mid_data_table_1.transtype='rongzi',mid_data_table_1.amount,0) rongzi_amount,
    if(mid_data_table_1.transtype='rongzi',mid_data_table_1.cd,0) rongzi_cd,
    if(mid_data_table_1.transtype='rongzi',mid_data_table_1.txn_dt,0) rongzi_txn_dt,
    if(mid_data_table_1.transtype='xiaofei',mid_data_table_1.amount,0) xiaofei_amount,
    if(mid_data_table_1.transtype='xiaofei',mid_data_table_1.cd,0) xiaofei_cd,
    if(mid_data_table_1.transtype='xiaofei',mid_data_table_1.txn_dt,0) xiaofei_txn_dt,
    if(mid_data_table_1.transtype='zhuanzhang',mid_data_table_1.amount,0) zhuanzhang_amount,
    if(mid_data_table_1.transtype='zhuanzhang',mid_data_table_1.cd,0) zhuanzhang_cd,
    if(mid_data_table_1.transtype='zhuanzhang',mid_data_table_1.txn_dt,0) zhuanzhang_txn_dt,
    if(mid_data_table_1.transtype='cunqu',mid_data_table_1.amount,0) cunqu_amount,
    if(mid_data_table_1.transtype='cunqu',mid_data_table_1.cd,0) cunqu_cd,
    if(mid_data_table_1.transtype='cunqu',mid_data_table_1.txn_dt,0) cunqu_txn_dt,
    if(mid_data_table_1.transtype='other',mid_data_table_1.amount,0) other_amount,
    if(mid_data_table_1.transtype='other',mid_data_table_1.cd,0) other_cd
    if(mid_data_table_1.transtype='other',mid_data_table_1.txn_dt,0) other_txn_dt
from mid_data_table_1;





--todo 创建1天的视图
create view mid_data_table_oneday as
select
        et,
        -- 消费相关
        sum(if xiaofei_amount!=0,1,0) over w xiaofei_01,
        sum(xiaofei_amount) over w xiaofei_02,
        max (xiaofei_amount) over w xiaofei_03,
        if(max (xiaofei_amount)!=0,1,0) over w xiaofei_04,
        sum(if xiaofei_amount!=0,1,0)/1 over w   xiaofei_05,
        sum(xiaofei_amount)/1  over w xiaofei_06,
        0.5                     xiaofei_07,    
        1                       xiaofei_08, 
        1                       xiaofei_09, 
        -- 办公相关
        sum(if bangong_amount!=0,1,0) over w bangong_01,
        sum(bangong_amount) over w bangong_02,
        max (bangong_amount)over w bangong_03,
        if(max (bangong_amount)!=0,1,0) over w bangong_04,
        sum(if bangong_amount!=0,1,0)/1 over w  bangong_05,
        sum(bangong_amount)/1 over w bangong_06,
        0.5                     bangong_07,    
        1                       bangong_08, 
        1                       bangong_09, 
        --薪资相关
        sum(if xinzi_amount!=0,1,0) over w xinzi_01,
        sum(xinzi_amount)over w xinzi_02,
        max (xinzi_amount)over w xinzi_03,
        if(max (xinzi_amount)!=0,1,0)over w xinzi_04,
        sum(if xinzi_amount!=0,1,0)/1 over w  xinzi_05,
        sum(xinzi_amount)/1 over w xinzi_06,
        0.5                     xinzi_07,    
        1                       xinzi_08, 
        1                       xinzi_09, 
        --保险相关
        sum(if baoxian_amount!=0,1,0) over w baoxian_01,
        sum(baoxian_amount)over w baoxian_02,
        max (baoxian_amount)over w baoxian_03,
        if(max (baoxian_amount)!=0,1,0)over w baoxian_04,
        sum(if baoxian_amount!=0,1,0)/1 over w  baoxian_05,
        sum(baoxian_amount)/1 over w baoxian_06,
        0.5                     baoxian_07,    
        1                       baoxian_08, 
        1                       baoxian_09,     
        --投资相关
        sum(if touzi_amount!=0,1,0) over w touzi_01,
        sum(touzi_amount)over w touzi_02,
        max (touzi_amount)over w touzi_03,
        if(max (touzi_amount)!=0,1,0)over w touzi_04,
        sum(if touzi_amount!=0,1,0)/1 over w  touzi_05,
        sum(touzi_amount)/1 over w  touzi_06,
        0.5                     touzi_07,    
        1                       touzi_08, 
        1                       touzi_09,     
        -- 融资相关
        sum(if rongzi_amount!=0,1,0) over w rongzi_01,
        sum(rongzi_amount) over w rongzi_02,
        max (rongzi_amount) over w rongzi_03,
        if(max (rongzi_amount)!=0,1,0)over w  rongzi_04,
        sum(if rongzi_amount!=0,1,0)/1 over w  rongzi_05,
        sum(rongzi_amount)/1 over w rongzi_06,
        0.5                     rongzi_07,    
        1                       rongzi_08, 
        1                       rongzi_09,     
        -- 转账相关
        sum(if zhuanzhang_amount!=0,1,0) over w zhuanzhang_01,
        sum(zhuanzhang_amount)over w zhuanzhang_02,
        max (zhuanzhang_amount)over w zhuanzhang_03,
        if(max (zhuanzhang_amount)!=0,1,0)over w zhuanzhang_04,
        sum(if zhuanzhang_amount!=0,1,0)/1 over w  zhuanzhang_05,
        sum(zhuanzhang_amount)/1 over w zhuanzhang_06,
        0.5                     zhuanzhang_07,    
        1                       zhuanzhang_08, 
        1                       zhuanzhang_09,     
        -- 存取相关
        sum(if cunqu_amount!=0,1,0) over w cunqu_01,
        sum(cunqu_amount) over w cunqu_02,
        max (cunqu_amount) over w cunqu_03,
        if(max (cunqu_amount)!=0,1,0)over w cunqu_04,
        sum(if cunqu_amount!=0,1,0)/1 over w  cunqu_05,
        sum(cunqu_amount)/1 over w cunqu_06,
        0.5                     cunqu_07,    
        1                       cunqu_08, 
        1                       cunqu_09,     
        -- 其他相关
        sum(if other_amount!=0,1,0) over w other_01,
        sum(other_amount) over w other_02,
        max (other_amount) over w other_03,
        if(max (other_amount)!=0,1,0) over w other_04,
        sum(if other_amount!=0,1,0)/1 over w  other_05,
        sum(other_amount)/1 over w other_06,
        0.5                     other_07,    
        1                       other_08, 
        1                       other_09     
from every_type_info_table
WINDOW w AS (PARTITION BY ttype order by et RANGE BETWEEN INTERVAL '1' DAY preceding AND CURRENT ROW);





--todo 创建3天的视图
create view mid_data_table_threeday as
select
        et,
-- 消费相关
        sum(if xiaofei_amount!=0,1,0) over w xiaofei_10,
        sum(xiaofei_amount) over w xiaofei_11,
        max (xiaofei_amount) over w xiaofei_12,
        count(distinct day(xiaofei_txn_dt)) over w xiaofei_13,
        sum(if xiaofei_amount!=0,1,0)/3 over w   xiaofei_14,
        sum(xiaofei_amount)/3  over w xiaofei_15,
        0.5                     xiaofei_16,
        3 xiaofei_17,
        3 xiaofei_18,
        if(count(distinct day(txn_dt)) over w =3,'是','否') xiaofei_19,
-- 办公相关
        sum(if bangong_amount!=0,1,0) over w bangong_10,
        sum(bangong_amount) over w bangong_11,
        max (bangong_amount) over w bangong_12,
        count(distinct day(bangong_txn_dt)) over w bangong_13,
        sum(if bangong_amount!=0,1,0)/3 over w   bangong_14,
        sum(bangong_amount)/3  over w bangong_15,
        0.5                     bangong_16,
        3 bangong_17,
        3 bangong_18,
        if(count(distinct day(txn_dt)) over w =3,'是','否') bangong_19,
--薪资相关
        sum(if rongzi_amount!=0,1,0) over w rongzi_10,
        sum(rongzi_amount) over w rongzi_11,
        max (rongzi_amount) over w rongzi_12,
        count(distinct day(rongzi_txn_dt)) over w rongzi_13,
        sum(if rongzi_amount!=0,1,0)/3 over w   rongzi_14,
        sum(rongzi_amount)/3  over w rongzi_15,
        0.5                     rongzi_16,
        3 rongzi_17,
        3 rongzi_18,
        if(count(distinct day(txn_dt)) over w =3,'是','否') rongzi_19,
--保险相关
        sum(if baoxian_amount!=0,1,0) over w baoxian_10,
        sum(baoxian_amount) over w baoxian_11,
        max (baoxian_amount) over w baoxian_12,
        count(distinct day(baoxian_txn_dt)) over w baoxian_13,
        sum(if baoxian_amount!=0,1,0)/3 over w   baoxian_14,
        sum(baoxian_amount)/3  over w baoxian_15,
        0.5                     baoxian_16,
        3 baoxian_17,
        3 baoxian_18,
        if(count(distinct day(txn_dt)) over w =3,'是','否') baoxian_19,
--投资相关
        sum(if touzi_amount!=0,1,0) over w touzi_10,
        sum(touzi_amount) over w touzi_11,
        max (touzi_amount) over w touzi_12,
        count(distinct day(touzi_txn_dt)) over w touzi_13,
        sum(if touzi_amount!=0,1,0)/3 over w   touzi_14,
        sum(touzi_amount)/3  over w touzi_15,
        0.5                     touzi_16,
        3 touzi_17,
        3 touzi_18,
        if(count(distinct day(txn_dt)) over w =3,'是','否') touzi_19,
--融资相关
        sum(if rongzi_amount!=0,1,0) over w rongzi_10,
        sum(rongzi_amount) over w rongzi_11,
        max (rongzi_amount) over w rongzi_12,
        count(distinct day(rongzi_txn_dt)) over w rongzi_13,
        sum(if rongzi_amount!=0,1,0)/3 over w   rongzi_14,
        sum(rongzi_amount)/3  over w rongzi_15,
        0.5                     rongzi_16,
        3 rongzi_17,
        3 rongzi_18,
        if(count(distinct day(txn_dt)) over w =3,'是','否') rongzi_19,
-- 转账相关
        sum(if zhuanzhang_amount!=0,1,0) over w zhuanzhang_10,
        sum(zhuanzhang_amount) over w zhuanzhang_11,
        max (zhuanzhang_amount) over w zhuanzhang_12,
        count(distinct day(zhuanzhang_txn_dt)) over w zhuanzhang_13,
        sum(if zhuanzhang_amount!=0,1,0)/3 over w   zhuanzhang_14,
        sum(zhuanzhang_amount)/3  over w zhuanzhang_15,
        0.5                     zhuanzhang_16,
        3 zhuanzhang_17,
        3 zhuanzhang_18,
        if(count(distinct day(txn_dt)) over w =3,'是','否') zhuanzhang_19,
-- 存取相关
        sum(if cunqu_amount!=0,1,0) over w cunqu_10,
        sum(cunqu_amount) over w cunqu_11,
        max (cunqu_amount) over w cunqu_12,
        count(distinct day(cunqu_txn_dt)) over w cunqu_13,
        sum(if cunqu_amount!=0,1,0)/3 over w   cunqu_14,
        sum(cunqu_amount)/3  over w cunqu_15,
        0.5                     cunqu_16,
        3 cunqu_17,
        3 cunqu_18,
        if(count(distinct day(txn_dt)) over w =3,'是','否') cunqu_19,
-- 其他相关
        sum(if other_amount!=0,1,0) over w other_10,
        sum(other_amount) over w other_11,
        max (other_amount) over w other_12,
        count(distinct day(other_txn_dt)) over w other_13,
        sum(if other_amount!=0,1,0)/3 over w   other_14,
        sum(other_amount)/3  over w other_15,
        0.5                     other_16,
        3 other_17,
        3 other_18,
        if(count(distinct day(txn_dt)) over w =3,'是','否') other_19
from every_type_info_table
WINDOW w AS (PARTITION BY ttype order by et RANGE BETWEEN INTERVAL '3' DAY preceding AND CURRENT ROW);





--todo 先整合 1天和 3天的数据
create view mid_data_table_3 as
select
        mid_data_table_oneday.xiaofei_01 as xiaofei_01,
        mid_data_table_oneday.xiaofei_02 as xiaofei_02,
        mid_data_table_oneday.xiaofei_03 as xiaofei_03,
        mid_data_table_oneday.xiaofei_04 as xiaofei_04,
        mid_data_table_oneday.xiaofei_05 as xiaofei_05,
        mid_data_table_oneday.xiaofei_06 as xiaofei_06,
        mid_data_table_oneday.xiaofei_07 as xiaofei_07,
        mid_data_table_oneday.xiaofei_08 as xiaofei_08,
        mid_data_table_oneday.xiaofei_09 as xiaofei_09,
        mid_data_table_threeday.xiaofei_10 as xiaofei_10,
        mid_data_table_threeday.xiaofei_11 as xiaofei_11,
        mid_data_table_threeday.xiaofei_12 as xiaofei_12,
        mid_data_table_threeday.xiaofei_13 as xiaofei_13,
        mid_data_table_threeday.xiaofei_14 as xiaofei_14,
        mid_data_table_threeday.xiaofei_15 as xiaofei_15,
        mid_data_table_threeday.xiaofei_16 as xiaofei_16,
        mid_data_table_threeday.xiaofei_17 as xiaofei_17,
        mid_data_table_threeday.xiaofei_18 as xiaofei_18,
        mid_data_table_threeday.xiaofei_19 as xiaofei_19,
        mid_data_table_oneday.bangong_01 as bangong_01,
        mid_data_table_oneday.bangong_02 as bangong_02,
        mid_data_table_oneday.bangong_03 as bangong_03,
        mid_data_table_oneday.bangong_04 as bangong_04,
        mid_data_table_oneday.bangong_05 as bangong_05,
        mid_data_table_oneday.bangong_06 as bangong_06,
        mid_data_table_oneday.bangong_07 as bangong_07,
        mid_data_table_oneday.bangong_08 as bangong_08,
        mid_data_table_oneday.bangong_09 as bangong_09,
        mid_data_table_threeday.bangong_10 as bangong_10,
        mid_data_table_threeday.bangong_11 as bangong_11,
        mid_data_table_threeday.bangong_12 as bangong_12,
        mid_data_table_threeday.bangong_13 as bangong_13,
        mid_data_table_threeday.bangong_14 as bangong_14,
        mid_data_table_threeday.bangong_15 as bangong_15,
        mid_data_table_threeday.bangong_16 as bangong_16,
        mid_data_table_threeday.bangong_17 as bangong_17,
        mid_data_table_threeday.bangong_18 as bangong_18,
        mid_data_table_threeday.bangong_19 as bangong_19,
        mid_data_table_oneday.xinzi_01 as xinzi_01,
        mid_data_table_oneday.xinzi_02 as xinzi_02,
        mid_data_table_oneday.xinzi_03 as xinzi_03,
        mid_data_table_oneday.xinzi_04 as xinzi_04,
        mid_data_table_oneday.xinzi_05 as xinzi_05,
        mid_data_table_oneday.xinzi_06 as xinzi_06,
        mid_data_table_oneday.xinzi_07 as xinzi_07,
        mid_data_table_oneday.xinzi_08 as xinzi_08,
        mid_data_table_oneday.xinzi_09 as xinzi_09,
        mid_data_table_threeday.xinzi_10 as xinzi_10,
        mid_data_table_threeday.xinzi_11 as xinzi_11,
        mid_data_table_threeday.xinzi_12 as xinzi_12,
        mid_data_table_threeday.xinzi_13 as xinzi_13,
        mid_data_table_threeday.xinzi_14 as xinzi_14,
        mid_data_table_threeday.xinzi_15 as xinzi_15,
        mid_data_table_threeday.xinzi_16 as xinzi_16,
        mid_data_table_threeday.xinzi_17 as xinzi_17,
        mid_data_table_threeday.xinzi_18 as xinzi_18,
        mid_data_table_threeday.xinzi_19 as xinzi_19,
        mid_data_table_oneday.baoxian_01 as baoxian_01,
        mid_data_table_oneday.baoxian_02 as baoxian_02,
        mid_data_table_oneday.baoxian_03 as baoxian_03,
        mid_data_table_oneday.baoxian_04 as baoxian_04,
        mid_data_table_oneday.baoxian_05 as baoxian_05,
        mid_data_table_oneday.baoxian_06 as baoxian_06,
        mid_data_table_oneday.baoxian_07 as baoxian_07,
        mid_data_table_oneday.baoxian_08 as baoxian_08,
        mid_data_table_oneday.baoxian_09 as baoxian_09,
        mid_data_table_threeday.baoxian_10 as baoxian_10,
        mid_data_table_threeday.baoxian_11 as baoxian_11,
        mid_data_table_threeday.baoxian_12 as baoxian_12,
        mid_data_table_threeday.baoxian_13 as baoxian_13,
        mid_data_table_threeday.baoxian_14 as baoxian_14,
        mid_data_table_threeday.baoxian_15 as baoxian_15,
        mid_data_table_threeday.baoxian_16 as baoxian_16,
        mid_data_table_threeday.baoxian_17 as baoxian_17,
        mid_data_table_threeday.baoxian_18 as baoxian_18,
        mid_data_table_threeday.baoxian_19 as baoxian_19,
        mid_data_table_oneday.touzi_01 as touzi_01,
        mid_data_table_oneday.touzi_02 as touzi_02,
        mid_data_table_oneday.touzi_03 as touzi_03,
        mid_data_table_oneday.touzi_04 as touzi_04,
        mid_data_table_oneday.touzi_05 as touzi_05,
        mid_data_table_oneday.touzi_06 as touzi_06,
        mid_data_table_oneday.touzi_07 as touzi_07,
        mid_data_table_oneday.touzi_08 as touzi_08,
        mid_data_table_oneday.touzi_09 as touzi_09,
        mid_data_table_threeday.touzi_10 as touzi_10,
        mid_data_table_threeday.touzi_11 as touzi_11,
        mid_data_table_threeday.touzi_12 as touzi_12,
        mid_data_table_threeday.touzi_13 as touzi_13,
        mid_data_table_threeday.touzi_14 as touzi_14,
        mid_data_table_threeday.touzi_15 as touzi_15,
        mid_data_table_threeday.touzi_16 as touzi_16,
        mid_data_table_threeday.touzi_17 as touzi_17,
        mid_data_table_threeday.touzi_18 as touzi_18,
        mid_data_table_threeday.touzi_19 as touzi_19,
        mid_data_table_oneday.rongzi_01 as rongzi_01,
        mid_data_table_oneday.rongzi_02 as rongzi_02,
        mid_data_table_oneday.rongzi_03 as rongzi_03,
        mid_data_table_oneday.rongzi_04 as rongzi_04,
        mid_data_table_oneday.rongzi_05 as rongzi_05,
        mid_data_table_oneday.rongzi_06 as rongzi_06,
        mid_data_table_oneday.rongzi_07 as rongzi_07,
        mid_data_table_oneday.rongzi_08 as rongzi_08,
        mid_data_table_oneday.rongzi_09 as rongzi_09,
        mid_data_table_threeday.rongzi_10 as rongzi_10,
        mid_data_table_threeday.rongzi_11 as rongzi_11,
        mid_data_table_threeday.rongzi_12 as rongzi_12,
        mid_data_table_threeday.rongzi_13 as rongzi_13,
        mid_data_table_threeday.rongzi_14 as rongzi_14,
        mid_data_table_threeday.rongzi_15 as rongzi_15,
        mid_data_table_threeday.rongzi_16 as rongzi_16,
        mid_data_table_threeday.rongzi_17 as rongzi_17,
        mid_data_table_threeday.rongzi_18 as rongzi_18,
        mid_data_table_threeday.rongzi_19 as rongzi_19,
        mid_data_table_oneday.zhuanzhang_01 as zhuanzhang_01,
        mid_data_table_oneday.zhuanzhang_02 as zhuanzhang_02,
        mid_data_table_oneday.zhuanzhang_03 as zhuanzhang_03,
        mid_data_table_oneday.zhuanzhang_04 as zhuanzhang_04,
        mid_data_table_oneday.zhuanzhang_05 as zhuanzhang_05,
        mid_data_table_oneday.zhuanzhang_06 as zhuanzhang_06,
        mid_data_table_oneday.zhuanzhang_07 as zhuanzhang_07,
        mid_data_table_oneday.zhuanzhang_08 as zhuanzhang_08,
        mid_data_table_oneday.zhuanzhang_09 as zhuanzhang_09,
        mid_data_table_threeday.zhuanzhang_10 as zhuanzhang_10,
        mid_data_table_threeday.zhuanzhang_11 as zhuanzhang_11,
        mid_data_table_threeday.zhuanzhang_12 as zhuanzhang_12,
        mid_data_table_threeday.zhuanzhang_13 as zhuanzhang_13,
        mid_data_table_threeday.zhuanzhang_14 as zhuanzhang_14,
        mid_data_table_threeday.zhuanzhang_15 as zhuanzhang_15,
        mid_data_table_threeday.zhuanzhang_16 as zhuanzhang_16,
        mid_data_table_threeday.zhuanzhang_17 as zhuanzhang_17,
        mid_data_table_threeday.zhuanzhang_18 as zhuanzhang_18,
        mid_data_table_threeday.zhuanzhang_19 as zhuanzhang_19,
        mid_data_table_oneday.cunqu_01 as cunqu_01,
        mid_data_table_oneday.cunqu_02 as cunqu_02,
        mid_data_table_oneday.cunqu_03 as cunqu_03,
        mid_data_table_oneday.cunqu_04 as cunqu_04,
        mid_data_table_oneday.cunqu_05 as cunqu_05,
        mid_data_table_oneday.cunqu_06 as cunqu_06,
        mid_data_table_oneday.cunqu_07 as cunqu_07,
        mid_data_table_oneday.cunqu_08 as cunqu_08,
        mid_data_table_oneday.cunqu_09 as cunqu_09,
        mid_data_table_threeday.cunqu_10 as cunqu_10,
        mid_data_table_threeday.cunqu_11 as cunqu_11,
        mid_data_table_threeday.cunqu_12 as cunqu_12,
        mid_data_table_threeday.cunqu_13 as cunqu_13,
        mid_data_table_threeday.cunqu_14 as cunqu_14,
        mid_data_table_threeday.cunqu_15 as cunqu_15,
        mid_data_table_threeday.cunqu_16 as cunqu_16,
        mid_data_table_threeday.cunqu_17 as cunqu_17,
        mid_data_table_threeday.cunqu_18 as cunqu_18,
        mid_data_table_threeday.cunqu_19 as cunqu_19,
        mid_data_table_oneday.other_01 as other_01,
        mid_data_table_oneday.other_02 as other_02,
        mid_data_table_oneday.other_03 as other_03,
        mid_data_table_oneday.other_04 as other_04,
        mid_data_table_oneday.other_05 as other_05,
        mid_data_table_oneday.other_06 as other_06,
        mid_data_table_oneday.other_07 as other_07,
        mid_data_table_oneday.other_08 as other_08,
        mid_data_table_oneday.other_09 as other_09,
        mid_data_table_threeday.other_10 as other_10,
        mid_data_table_threeday.other_11 as other_11,
        mid_data_table_threeday.other_12 as other_12,
        mid_data_table_threeday.other_13 as other_13,
        mid_data_table_threeday.other_14 as other_14,
        mid_data_table_threeday.other_15 as other_15,
        mid_data_table_threeday.other_16 as other_16,
        mid_data_table_threeday.other_17 as other_17,
        mid_data_table_threeday.other_18 as other_18,
        mid_data_table_threeday.other_19 as other_19
from mid_data_table_oneday,mid_data_table_threeday
where mid_data_table_threeday.et=mid_data_table_oneday.et
and mid_data_table_oneday.et BETWEEN mid_data_table_threeday.et - INTERVAL '2' second AND mid_data_table_threeday.et + INTERVAL '2' second;


-- todo 三天是否连续相关视图
-- select TIMESTAMPDIFF(DAY, TIMESTAMP '2003-01-02 10:00:00', TIMESTAMP '2003-01-01 10:00:00');结果为-1，是后边的日期-前边的日期

-- 前10s的总和
create viwe one_day_before_amount as
select
        ts,
        sum(every_type_info_table.xiaofei_amount) over (partition by rulecode order by ts range between interval '10' second and current row) as one_xiaofei_amount,
        sum(every_type_info_table.bangong_amount) over (partition by rulecode order by ts range between interval '10' second and current row) as one_bangong_amount,
        sum(every_type_info_table.xinzi_amount) over (partition by rulecode order by ts range between interval '10' second and current row) as one_xinzi_amount,
        sum(every_type_info_table.baoxian_amount) over (partition by rulecode order by ts range between interval '10' second and current row) as one_baoxian_amount,
        sum(every_type_info_table.touzi_amount) over (partition by rulecode order by ts range between interval '10' second and current row) as one_touzi_amount,
        sum(every_type_info_table.rongzi_amount) over (partition by rulecode order by ts range between interval '10' second and current row) as one_rongzi_amount,
        sum(every_type_info_table.zhuanzhang_amount) over (partition by rulecode order by ts range between interval '10' second and current row) as one_zhuanzhang_amount,
        sum(every_type_info_table.qunqu_amount) over (partition by rulecode order by ts range between interval '10' second and current row) as one_cunqu_amount,
        sum(every_type_info_table.other_amount) over (partition by rulecode order by ts range between interval '10' second and current row) as one_other_amount
from every_type_info_table;


-- 前20s的总和
create viwe two_day_before_amount as
select
        ts,
        sum(every_type_info_table.xiaofei_amount) over (partition by rulecode order by ts range between interval '20' second and current row) as two_xiaofei_amount,
        sum(every_type_info_table.bangong_amount) over (partition by rulecode order by ts range between interval '20' second and current row) as two_bangong_amount,
        sum(every_type_info_table.xinzi_amount) over (partition by rulecode order by ts range between interval '20' second and current row) as two_xinzi_amount,
        sum(every_type_info_table.baoxian_amount) over (partition by rulecode order by ts range between interval '20' second and current row) as two_baoxian_amount,
        sum(every_type_info_table.touzi_amount) over (partition by rulecode order by ts range between interval '20' second and current row) as two_touzi_amount,
        sum(every_type_info_table.rongzi_amount) over (partition by rulecode order by ts range between interval '20' second and current row) as two_rongzi_amount,
        sum(every_type_info_table.zhuanzhang_amount) over (partition by rulecode order by ts range between interval '20' second and current row) as two_zhuanzhang_amount,
        sum(every_type_info_table.qunqu_amount) over (partition by rulecode order by ts range between interval '20' second and current row) as two_cunqu_amount,
        sum(every_type_info_table.other_amount) over (partition by rulecode order by ts range between interval '20' second and current row) as two_other_amount
from every_type_info_table;


-- 前30s的总和
create viwe three_day_before_amount as
select
        ts,
        sum(every_type_info_table.xiaofei_amount) over (partition by rulecode order by ts range between interval '20' second and current row) as three_xiaofei_amount,
        sum(every_type_info_table.bangong_amount) over (partition by rulecode order by ts range between interval '20' second and current row) as three_bangong_amount,
        sum(every_type_info_table.xinzi_amount) over (partition by rulecode order by ts range between interval '20' second and current row) as three_xinzi_amount,
        sum(every_type_info_table.baoxian_amount) over (partition by rulecode order by ts range between interval '20' second and current row) as three_baoxian_amount,
        sum(every_type_info_table.touzi_amount) over (partition by rulecode order by ts range between interval '20' second and current row) as three_touzi_amount,
        sum(every_type_info_table.rongzi_amount) over (partition by rulecode order by ts range between interval '20' second and current row) as three_rongzi_amount,
        sum(every_type_info_table.zhuanzhang_amount) over (partition by rulecode order by ts range between interval '20' second and current row) as three_zhuanzhang_amount,
        sum(every_type_info_table.qunqu_amount) over (partition by rulecode order by ts range between interval '20' second and current row) as three_cunqu_amount,
        sum(every_type_info_table.other_amount) over (partition by rulecode order by ts range between interval '20' second and current row) as three_other_amount
from every_type_info_table;


--前1天总和 前2天总和 interval join
create view one_two_amount_table as
select
        oneday.ts as ts,
--前一天
        oneday.one_xiaofei_amount as one_xiaofei_amount,
        oneday.one_bangong_amount as one_bangong_amount,
        oneday.one_xinzi_amount as one_xinzi_amount,
        oneday.one_baoxian_amount as one_baoxian_amount,
        oneday.one_touzi_amount as one_touzi_amount,
        oneday.one_rongzi_amount as one_rongzi_amount,
        oneday.one_zhuanzhang_amount as one_zhuanzhang_amount,
        oneday.one_cunqu_amount as one_cunqu_amount,
        oneday.one_other_amount as one_other_amount,
--前两天
        twoday.two_xiaofei_amount - oneday.one_xiaofei_amount as two_xiaofei_amount,
        twoday.two_bangong_amount - oneday.one_bangong_amount as two_bangong_amount,
        twoday.two_xinzi_amount - oneday.one_xinzi_amount as two_xinzi_amount,
        twoday.two_baoxian_amount - oneday.one_baoxian_amount as two_baoxian_amount,
        twoday.two_touzi_amount - oneday.one_touzi_amount as two_touzi_amount,
        twoday.two_rongzi_amount - oneday.one_rongzi_amount as two_rongzi_amount,
        twoday.two_zhuanzhang_amount - oneday.one_zhuanzhang_amount as two_zhuanzhang_amount,
        twoday.two_cunqu_amount - oneday.one_cunqu_amount as two_cunqu_amount,
        twoday.two_other_amount - oneday.one_other_amount as two_other_amount
from one_day_before_amount as oneday,two_day_before_amount as twoday
where oneday.ts=twoday.ts
      and oneday.ts BETWEEN twoday.ts - INTERVAL '1' second AND twoday.ts + INTERVAL '1' second


-- 和前3天 interval join
create view one_two_three_amount_table
select
        t1.ts as ts,
        t1.one_xiaofei_amount       as one_xiaofei_amount,
        t1.one_bangong_amount       as one_bangong_amount,
        t1.one_xinzi_amount         as one_xinzi_amount,
        t1.one_baoxian_amount       as one_baoxian_amount,
        t1.one_touzi_amount         as one_touzi_amount,
        t1.one_rongzi_amount        as one_rongzi_amount,
        t1.one_zhuanzhang_amount    as one_zhuanzhang_amount,
        t1.one_cunqu_amount         as one_cunqu_amount,
        t1.one_other_amount         as one_other_amount,
--2天前的数据
        t1.two_xiaofei_amount       as two_xiaofei_amount,
        t1.two_bangong_amount       as two_bangong_amount,
        t1.two_xinzi_amount         as two_xinzi_amount,
        t1.two_baoxian_amount       as two_baoxian_amount,
        t1.two_touzi_amount         as two_touzi_amount,
        t1.two_rongzi_amount        as two_rongzi_amount,
        t1.two_zhuanzhang_amount    as two_zhuanzhang_amount,
        t1.two_cunqu_amount         as two_cunqu_amount,
        t1.two_other_amount         as two_other_amount,
--3天前的数据
        t2.three_xiaofei_amount - t1.one_xiaofei_amount - t1.two_xiaofei_amount         as three_xiaofei_amount,
        t2.three_xiaofei_amount - t1.one_bangong_amount - t1.two_bangong_amount         as three_bangong_amount,
        t2.three_xiaofei_amount - t1.one_xinzi_amount - t1.two_xinzi_amount             as three_xinzi_amount,
        t2.three_xiaofei_amount - t1.one_baoxian_amount - t1.two_baoxian_amount         as three_baoxian_amount,
        t2.three_xiaofei_amount - t1.one_touzi_amount - t1.two_touzi_amount             as three_touzi_amount,
        t2.three_xiaofei_amount - t1.one_rongzi_amount - t1.two_rongzi_amount           as three_rongzi_amount,
        t2.three_xiaofei_amount - t1.one_zhuanzhang_amount - t1.two_zhuanzhang_amount   as three_zhuanzhang_amount,
        t2.three_xiaofei_amount - t1.one_cunqu_amount - t1.two_cunqu_amount             as three_cunqu_amount,
        t2.three_xiaofei_amount - t1.one_other_amount - t1.two_other_amount             as three_other_amount
from one_two_amount_table t1,three_day_before_amount t2
where t1.ts=t2.ts
      and t1.ts BETWEEN t2.ts - INTERVAL '2' second AND t2.ts + INTERVAL '2' second


-- 判断3天的数据是否都>5万 10万 25万 50万
create view three_day_flage as
select
        ts as ts,
        one_xiaofei_amount > 50000          and     two_xiaofei_amount > 50000          and     three_xiaofei_amount > 50000     as xiaofei_5_flage,
        one_xiaofei_amount > 100000         and     two_xiaofei_amount > 100000         and     three_xiaofei_amount > 100000    as xiaofei_10_flage,
        one_xiaofei_amount > 250000         and     two_xiaofei_amount > 250000         and     three_xiaofei_amount > 250000    as xiaofei_25_flage,
        one_xiaofei_amount > 500000         and     two_xiaofei_amount > 500000         and     three_xiaofei_amount > 500000    as xiaofei_50_flage,
        one_bangong_amount > 50000          and     two_bangong_amount > 50000          and     three_bangong_amount > 50000     as bangong_5_flage,
        one_bangong_amount > 100000         and     two_bangong_amount > 100000         and     three_bangong_amount > 100000    as bangong_10_flage,
        one_bangong_amount > 250000         and     two_bangong_amount > 250000         and     three_bangong_amount > 250000    as bangong_25_flage,
        one_bangong_amount > 500000         and     two_bangong_amount > 500000         and     three_bangong_amount > 500000    as bangong_50_flage,
        one_xinzi_amount > 50000            and     two_xinzi_amount > 50000            and     three_xinzi_amount > 50000       as xinzi_5_flage,
        one_xinzi_amount > 100000           and     two_xinzi_amount > 100000           and     three_xinzi_amount > 100000      as xinzi_10_flage,
        one_xinzi_amount > 250000           and     two_xinzi_amount > 250000           and     three_xinzi_amount > 250000      as xinzi_25_flage,
        one_xinzi_amount > 500000           and     two_xinzi_amount > 500000           and     three_xinzi_amount > 500000      as xinzi_50_flage,
        one_baoxian_amount > 50000          and     two_baoxian_amount > 50000          and     three_baoxian_amount > 50000     as baoxian_5_flage,
        one_baoxian_amount > 100000         and     two_baoxian_amount > 100000         and     three_baoxian_amount > 100000    as baoxian_10_flage,
        one_baoxian_amount > 250000         and     two_baoxian_amount > 250000         and     three_baoxian_amount > 250000    as baoxian_25_flage,
        one_baoxian_amount > 500000         and     two_baoxian_amount > 500000         and     three_baoxian_amount > 500000    as baoxian_50_flage,
        one_touzi_amount > 50000            and     two_touzi_amount > 50000            and     three_touzi_amount > 50000       as touzi_5_flage,
        one_touzi_amount > 100000           and     two_touzi_amount > 100000           and     three_touzi_amount > 100000      as touzi_10_flage,
        one_touzi_amount > 250000           and     two_touzi_amount > 250000           and     three_touzi_amount > 250000      as touzi_25_flage,
        one_touzi_amount > 500000           and     two_touzi_amount > 500000           and     three_touzi_amount > 500000      as touzi_50_flage,
        one_rongzi_amount > 50000           and     two_rongzi_amount > 50000           and     three_rongzi_amount > 50000      as rongzi_5_flage,
        one_rongzi_amount > 100000          and     two_rongzi_amount > 100000          and     three_rongzi_amount > 100000     as rongzi_10_flage,
        one_rongzi_amount > 250000          and     two_rongzi_amount > 250000          and     three_rongzi_amount > 250000     as rongzi_25_flage,
        one_rongzi_amount > 500000          and     two_rongzi_amount > 500000          and     three_rongzi_amount > 500000     as rongzi_50_flage,
        one_zhuanzhang_amount > 50000       and     two_zhuanzhang_amount > 50000       and     three_zhuanzhang_amount > 50000  as zhuanzhang_5_flage,
        one_zhuanzhang_amount > 100000      and     two_zhuanzhang_amount > 100000      and     three_zhuanzhang_amount > 100000 as zhuanzhang_10_flage,
        one_zhuanzhang_amount > 250000      and     two_zhuanzhang_amount > 250000      and     three_zhuanzhang_amount > 250000 as zhuanzhang_25_flage,
        one_zhuanzhang_amount > 500000      and     two_zhuanzhang_amount > 500000      and     three_zhuanzhang_amount > 500000 as zhuanzhang_50_flage,
        one_cunqu_amount > 50000            and     two_cunqu_amount > 50000            and     three_cunqu_amount > 50000       as cunqu_5_flage,
        one_cunqu_amount > 100000           and     two_cunqu_amount > 100000           and     three_cunqu_amount > 100000      as cunqu_10_flage,
        one_cunqu_amount > 250000           and     two_cunqu_amount > 250000           and     three_cunqu_amount > 250000      as cunqu_25_flage,
        one_cunqu_amount > 500000           and     two_cunqu_amount > 500000           and     three_cunqu_amount > 500000      as cunqu_50_flage,
        one_other_amount > 50000            and     two_other_amount > 50000            and     three_other_amount > 50000       as other_5_flage,
        one_other_amount > 100000           and     two_other_amount > 100000           and     three_other_amount > 100000      as other_10_flage,
        one_other_amount > 250000           and     two_other_amount > 250000           and     three_other_amount > 250000      as other_25_flage,
        one_other_amount > 500000           and     two_other_amount > 500000           and     three_other_amount > 500000      as other_50_flage
from one_two_three_amount_table;


--最终结果 连接 mid_data_table_3  和  three_day_flage
insert into sink_table_1
select
        xiaofei_01,
        xiaofei_02,
        xiaofei_03,
        xiaofei_04,
        xiaofei_05,
        xiaofei_06,
        xiaofei_07,
        xiaofei_08,
        xiaofei_09,
        xiaofei_10,
        xiaofei_11,
        xiaofei_12,
        xiaofei_13,
        xiaofei_14,
        xiaofei_15,
        xiaofei_16,
        xiaofei_17,
        xiaofei_18,
        xiaofei_19,
        xiaofei_5_flage,
        xiaofei_10_flage,
        xiaofei_25_flage,
        xiaofei_50_flage,
        bangong_01,
        bangong_02,
        bangong_03,
        bangong_04,
        bangong_05,
        bangong_06,
        bangong_07,
        bangong_08,
        bangong_09,
        bangong_10,
        bangong_11,
        bangong_12,
        bangong_13,
        bangong_14,
        bangong_15,
        bangong_16,
        bangong_17,
        bangong_18,
        bangong_19,
        xinzi_01,
        xinzi_02,
        xinzi_03,
        xinzi_04,
        xinzi_05,
        xinzi_06,
        xinzi_07,
        xinzi_08,
        xinzi_09,
        xinzi_10,
        xinzi_11,
        xinzi_12,
        xinzi_13,
        xinzi_14,
        xinzi_15,
        xinzi_16,
        xinzi_17,
        xinzi_18,
        xinzi_19,
        xinzi_5_flage,
        xinzi_10_flage,
        xinzi_25_flage,
        xinzi_50_flage,
        baoxian_01,
        baoxian_02,
        baoxian_03,
        baoxian_04,
        baoxian_05,
        baoxian_06,
        baoxian_07,
        baoxian_08,
        baoxian_09,
        baoxian_10,
        baoxian_11,
        baoxian_12,
        baoxian_13,
        baoxian_14,
        baoxian_15,
        baoxian_16,
        baoxian_17,
        baoxian_18,
        baoxian_19,
        baoxian_5_flage,
        baoxian_10_flage,
        baoxian_25_flage,
        baoxian_50_flage,
        touzi_01,
        touzi_02,
        touzi_03,
        touzi_04,
        touzi_05,
        touzi_06,
        touzi_07,
        touzi_08,
        touzi_09,
        touzi_10,
        touzi_11,
        touzi_12,
        touzi_13,
        touzi_14,
        touzi_15,
        touzi_16,
        touzi_17,
        touzi_18,
        touzi_19,
        touzi_5_flage,
        touzi_10_flage,
        touzi_25_flage,
        touzi_50_flage,
        rongzi_01,
        rongzi_02,
        rongzi_03,
        rongzi_04,
        rongzi_05,
        rongzi_06,
        rongzi_07,
        rongzi_08,
        rongzi_09,
        rongzi_10,
        rongzi_11,
        rongzi_12,
        rongzi_13,
        rongzi_14,
        rongzi_15,
        rongzi_16,
        rongzi_17,
        rongzi_18,
        rongzi_19,
        rongzi_5_flage,
        rongzi_10_flage,
        rongzi_25_flage,
        rongzi_50_flage,
        zhuanzhang_01,
        zhuanzhang_02,
        zhuanzhang_03,
        zhuanzhang_04,
        zhuanzhang_05,
        zhuanzhang_06,
        zhuanzhang_07,
        zhuanzhang_08,
        zhuanzhang_09,
        zhuanzhang_10,
        zhuanzhang_11,
        zhuanzhang_12,
        zhuanzhang_13,
        zhuanzhang_14,
        zhuanzhang_15,
        zhuanzhang_16,
        zhuanzhang_17,
        zhuanzhang_18,
        zhuanzhang_19,
        zhuanzhang_5_flage,
        zhuanzhang_10_flage,
        zhuanzhang_25_flage,
        zhuanzhang_50_flage,
        cunqu_01,
        cunqu_02,
        cunqu_03,
        cunqu_04,
        cunqu_05,
        cunqu_06,
        cunqu_07,
        cunqu_08,
        cunqu_09,
        cunqu_10,
        cunqu_11,
        cunqu_12,
        cunqu_13,
        cunqu_14,
        cunqu_15,
        cunqu_16,
        cunqu_17,
        cunqu_18,
        cunqu_19,
        cunqu_5_flage,
        cunqu_10_flage,
        cunqu_25_flage,
        cunqu_50_flage,
        other_01,
        other_02,
        other_03,
        other_04,
        other_05,
        other_06,
        other_07,
        other_08,
        other_09,
        other_10,
        other_11,
        other_12,
        other_13,
        other_14,
        other_15,
        other_16,
        other_17,
        other_18,
        other_19,
        other_5_flage,
        other_10_flage,
        other_25_flage,
        other_50_flage
from mid_data_table_3,three_day_flage
where mid_data_table_3.ts=three_day_flage.ts
      and and mid_data_table_3.ts BETWEEN three_day_flage.ts - INTERVAL '2' second AND three_day_flage.ts + INTERVAL '2' second;
