
-- source表
CREATE TABLE source_table_1 (
      event_id STRING ,
      transtype string,
      amount BIGINT,
      cd BIGINT,
      txn_dt string,
      ts  BIGINT,
      et AS TO_TIMESTAMP(FROM_UNIXTIME(ts/1000,'yyyy-MM-dd HH:mm:ss')),
      WATERMARK FOR et AS et - INTERVAL '5' SECOND
    )
    WITH (
      'connector' = 'kafka',
      'topic' = 'qinghua001_source_table_1',
      'properties.group.id'='dev_flink',
      'properties.zookeeper.connect'='10.1.30.6:2181',
      'properties.bootstrap.servers' = '10.1.30.8:9092',
      'format' = 'json',
      'scan.startup.mode' = 'latest-offset'
      );


create table sink_table_1(
        xiaofei_01 bigint ,
        xiaofei_02 decimal ,
        xiaofei_03 decimal ,
        xiaofei_04 bigint ,
        xiaofei_05 bigint ,
        xiaofei_06 decimal ,
        xiaofei_07 FLOAT ,
        xiaofei_08 FLOAT ,
        xiaofei_09 FLOAT ,
        xiaofei_10 bigint ,
        xiaofei_11 DECIMAL(18,2) ,
        xiaofei_12 DECIMAL(18,2) ,
        xiaofei_13 bigint ,
        xiaofei_14 bigint ,
        xiaofei_15 DECIMAL(18,2) ,
        xiaofei_16 FLOAT ,
        xiaofei_17 FLOAT ,
        xiaofei_18 FLOAT ,
        xiaofei_19 string ,
        xiaofei_20 STRING ,
        xiaofei_21 STRING ,
        xiaofei_22 STRING ,
        xiaofei_23 STRING ,
        bangong_01 bigint ,
        bangong_02 decimal ,
        bangong_03 decimal ,
        bangong_04 bigint ,
        bangong_05 bigint ,
        bangong_06 decimal ,
        bangong_07 FLOAT ,
        bangong_08 FLOAT ,
        bangong_09 FLOAT ,
        bangong_10 bigint ,
        bangong_11 DECIMAL(18,2) ,
        bangong_12 DECIMAL(18,2) ,
        bangong_13 bigint ,
        bangong_14 bigint ,
        bangong_15 DECIMAL(18,2) ,
        bangong_16 FLOAT ,
        bangong_17 FLOAT ,
        bangong_18 FLOAT ,
        bangong_19 string ,
        bangong_20 STRING ,
        bangong_21 STRING ,
        bangong_22 STRING ,
        bangong_23 STRING ,
        xinzi_01 bigint ,
        xinzi_02 decimal ,
        xinzi_03 decimal ,
        xinzi_04 bigint ,
        xinzi_05 bigint ,
        xinzi_06 decimal ,
        xinzi_07 FLOAT ,
        xinzi_08 FLOAT ,
        xinzi_09 FLOAT ,
        xinzi_10 bigint ,
        xinzi_11 DECIMAL(18,2) ,
        xinzi_12 DECIMAL(18,2) ,
        xinzi_13 bigint ,
        xinzi_14 bigint ,
        xinzi_15 DECIMAL(18,2) ,
        xinzi_16 FLOAT ,
        xinzi_17 FLOAT ,
        xinzi_18 FLOAT ,
        xinzi_19 string ,
        xinzi_20 STRING ,
        xinzi_21 STRING ,
        xinzi_22 STRING ,
        xinzi_23 STRING ,
        baoxian_01 bigint ,
        baoxian_02 decimal ,
        baoxian_03 decimal ,
        baoxian_04 bigint ,
        baoxian_05 bigint ,
        baoxian_06 decimal ,
        baoxian_07 FLOAT ,
        baoxian_08 FLOAT ,
        baoxian_09 FLOAT ,
        baoxian_10 bigint ,
        baoxian_11 DECIMAL(18,2) ,
        baoxian_12 DECIMAL(18,2) ,
        baoxian_13 bigint ,
        baoxian_14 bigint ,
        baoxian_15 DECIMAL(18,2) ,
        baoxian_16 FLOAT ,
        baoxian_17 FLOAT ,
        baoxian_18 FLOAT ,
        baoxian_19 string ,
        baoxian_20 STRING ,
        baoxian_21 STRING ,
        baoxian_22 STRING ,
        baoxian_23 STRING ,
        touzi_01 bigint ,
        touzi_02 decimal ,
        touzi_03 decimal ,
        touzi_04 bigint ,
        touzi_05 bigint ,
        touzi_06 decimal ,
        touzi_07 FLOAT ,
        touzi_08 FLOAT ,
        touzi_09 FLOAT ,
        touzi_10 bigint ,
        touzi_11 DECIMAL(18,2) ,
        touzi_12 DECIMAL(18,2) ,
        touzi_13 bigint ,
        touzi_14 bigint ,
        touzi_15 DECIMAL(18,2) ,
        touzi_16 FLOAT ,
        touzi_17 FLOAT ,
        touzi_18 FLOAT ,
        touzi_19 string ,
        touzi_20 STRING ,
        touzi_21 STRING ,
        touzi_22 STRING ,
        touzi_23 STRING ,
        rongzi_01 bigint ,
        rongzi_02 decimal ,
        rongzi_03 decimal ,
        rongzi_04 bigint ,
        rongzi_05 bigint ,
        rongzi_06 decimal ,
        rongzi_07 FLOAT ,
        rongzi_08 FLOAT ,
        rongzi_09 FLOAT ,
        rongzi_10 bigint ,
        rongzi_11 DECIMAL(18,2) ,
        rongzi_12 DECIMAL(18,2) ,
        rongzi_13 bigint ,
        rongzi_14 bigint ,
        rongzi_15 DECIMAL(18,2) ,
        rongzi_16 FLOAT ,
        rongzi_17 FLOAT ,
        rongzi_18 FLOAT ,
        rongzi_19 string ,
        rongzi_20 STRING ,
        rongzi_21 STRING ,
        rongzi_22 STRING ,
        rongzi_23 STRING ,
        zhuanzhang_01 bigint ,
        zhuanzhang_02 decimal ,
        zhuanzhang_03 decimal ,
        zhuanzhang_04 bigint ,
        zhuanzhang_05 bigint ,
        zhuanzhang_06 decimal ,
        zhuanzhang_07 FLOAT ,
        zhuanzhang_08 FLOAT ,
        zhuanzhang_09 FLOAT ,
        zhuanzhang_10 bigint ,
        zhuanzhang_11 DECIMAL(18,2) ,
        zhuanzhang_12 DECIMAL(18,2) ,
        zhuanzhang_13 bigint ,
        zhuanzhang_14 bigint ,
        zhuanzhang_15 DECIMAL(18,2) ,
        zhuanzhang_16 FLOAT ,
        zhuanzhang_17 FLOAT ,
        zhuanzhang_18 FLOAT ,
        zhuanzhang_19 string ,
        zhuanzhang_20 STRING ,
        zhuanzhang_21 STRING ,
        zhuanzhang_22 STRING ,
        zhuanzhang_23 STRING ,
        cunqu_01 bigint ,
        cunqu_02 decimal ,
        cunqu_03 decimal ,
        cunqu_04 bigint ,
        cunqu_05 bigint ,
        cunqu_06 decimal ,
        cunqu_07 FLOAT ,
        cunqu_08 FLOAT ,
        cunqu_09 FLOAT ,
        cunqu_10 bigint ,
        cunqu_11 DECIMAL(18,2) ,
        cunqu_12 DECIMAL(18,2) ,
        cunqu_13 bigint ,
        cunqu_14 bigint ,
        cunqu_15 DECIMAL(18,2) ,
        cunqu_16 FLOAT ,
        cunqu_17 FLOAT ,
        cunqu_18 FLOAT ,
        cunqu_19 string ,
        cunqu_20 STRING ,
        cunqu_21 STRING ,
        cunqu_22 STRING ,
        cunqu_23 STRING ,
        other_01 bigint ,
        other_02 decimal ,
        other_03 decimal ,
        other_04 bigint ,
        other_05 bigint ,
        other_06 decimal ,
        other_07 FLOAT ,
        other_08 FLOAT ,
        other_09 FLOAT ,
        other_10 bigint ,
        other_11 DECIMAL(18,2) ,
        other_12 DECIMAL(18,2) ,
        other_13 bigint ,
        other_14 bigint ,
        other_15 DECIMAL(18,2) ,
        other_16 FLOAT ,
        other_17 FLOAT ,
        other_18 FLOAT ,
        other_19 string ,
        other_20 STRING ,
        other_21 STRING ,
        other_22 STRING ,
        other_23 STRING)
		WITH (
      'connector' = 'kafka',
      'topic' = 'qinghua001_sink_table_1',
      'properties.group.id'='dev_flink',
      'properties.zookeeper.connect'='10.1.30.6:2181',
      'properties.bootstrap.servers' = '10.1.30.8:9092',
      'format' = 'json',
      'scan.startup.mode' = 'latest-offset'
      );

create view every_type_info_table as
select
    et,
    if(transtype='xiaofei',amount,0) xiaofei_amount,
    if(transtype='xiaofei',cd,0) xiaofei_cd,
    if(transtype='xiaofei',txn_dt,'0') xiaofei_txn_dt,
    if(transtype='bangong',amount,0) bangong_amount,
    if(transtype='bangong',cd,0) bangong_cd,
    if(transtype='bangong',txn_dt,'0') bangong_txn_dt,
    if(transtype='xinzi',amount,0) xinzi_amount,
    if(transtype='xinzi',cd,0) xinzi_cd,
    if(transtype='xinzi',txn_dt,'0') xinzi_txn_dt,
    if(transtype='baoxian',amount,0) baoxian_amount,
    if(transtype='baoxian',cd,0) baoxian_cd,
    if(transtype='baoxian',txn_dt,'0') baoxian_txn_dt,
    if(transtype='touzi',amount,0) touzi_amount,
    if(transtype='touzi',cd,0) touzi_cd,
    if(transtype='touzi',txn_dt,'0') touzi_txn_dt,
    if(transtype='rongzi',amount,0) rongzi_amount,
    if(transtype='rongzi',cd,0) rongzi_cd,
    if(transtype='rongzi',txn_dt,'0') rongzi_txn_dt,
    if(transtype='xiaofei',amount,0) xiaofei_amount,
    if(transtype='xiaofei',cd,0) xiaofei_cd,
    if(transtype='xiaofei',txn_dt,'0') xiaofei_txn_dt,
    if(transtype='zhuanzhang',amount,0) zhuanzhang_amount,
    if(transtype='zhuanzhang',cd,0) zhuanzhang_cd,
    if(transtype='zhuanzhang',txn_dt,'0') zhuanzhang_txn_dt,
    if(transtype='cunqu',amount,0) cunqu_amount,
    if(transtype='cunqu',cd,0) cunqu_cd,
    if(transtype='cunqu',txn_dt,'0') cunqu_txn_dt,
    if(transtype='other',amount,0) other_amount,
    if(transtype='other',cd,0) other_cd,
    if(transtype='other',txn_dt,'0') other_txn_dt
from source_table_1;

-- todo 创建1天的信息视图
create view mid_data_table_oneday as
select
        et,
         -- 消费相关
        sum(if (xiaofei_amount=0,0,1)) over w as xiaofei_01,
        max (xiaofei_amount) over w as xiaofei_03,
        sum(xiaofei_amount) over w as xiaofei_02,
        if(max (xiaofei_amount)over w =0,0,1)  as xiaofei_04,
        sum(if (xiaofei_amount=0,0,1)) over w   as xiaofei_05,
        sum(xiaofei_amount)  over w as xiaofei_06,
        0.5                     as xiaofei_07,
        1                       as xiaofei_08,
        1                       as xiaofei_09,
        -- 办公相关
        sum(if (bangong_amount=0,0,1)) over w bangong_01,
        sum(bangong_amount) over w bangong_02,
        max (bangong_amount)over w bangong_03,
        if(max (bangong_amount)over w =0,0,1)  bangong_04,
        sum(if (bangong_amount=0,0,1)) over w  bangong_05,
        sum(bangong_amount) over w bangong_06,
        0.5                     bangong_07,
        1                       bangong_08,
        1                       bangong_09,
        --薪资相关
        sum(if (xinzi_amount=0,0,1)) over w xinzi_01,
        sum(xinzi_amount)over w xinzi_02,
        max (xinzi_amount)over w xinzi_03,
        if(max (xinzi_amount)over w =0,0,1) xinzi_04,
        sum(if (xinzi_amount=0,0,1)) over w  xinzi_05,
        sum(xinzi_amount) over w xinzi_06,
        0.5                     xinzi_07,
        1                       xinzi_08,
        1                       xinzi_09,
        --保险相关
        sum(if (baoxian_amount=0,0,1)) over w baoxian_01,
        sum(baoxian_amount)over w baoxian_02,
        max (baoxian_amount)over w baoxian_03,
        if(max (baoxian_amount) over w =0,0,1) baoxian_04,
        sum(if (baoxian_amount=0,0,1)) over w  baoxian_05,
        sum(baoxian_amount) over w baoxian_06,
        0.5                     baoxian_07,
        1                       baoxian_08,
        1                       baoxian_09,
        --投资相关
        sum(if (touzi_amount=0,0,1)) over w touzi_01,
        sum(touzi_amount)over w touzi_02,
        max (touzi_amount)over w touzi_03,
        if(max (touzi_amount) over w =0,0,1) touzi_04,
        sum(if (touzi_amount=0,0,1)) over w  touzi_05,
        sum(touzi_amount) over w  touzi_06,
        0.5                     touzi_07,
        1                       touzi_08,
        1                       touzi_09,
        -- 融资相关
        sum(if (rongzi_amount=0,0,1)) over w rongzi_01,
        sum(rongzi_amount) over w rongzi_02,
        max (rongzi_amount) over w rongzi_03,
        if(max (rongzi_amount) over w =0,0,1)  rongzi_04,
        sum(if (rongzi_amount=0,0,1)) over w  rongzi_05,
        sum(rongzi_amount) over w rongzi_06,
        0.5                     rongzi_07,
        1                       rongzi_08,
        1                       rongzi_09,
        -- 转账相关
        sum(if (zhuanzhang_amount=0,0,1)) over w zhuanzhang_01,
        sum(zhuanzhang_amount)over w zhuanzhang_02,
        max (zhuanzhang_amount)over w zhuanzhang_03,
        if(max (zhuanzhang_amount) over w =0,0,1) zhuanzhang_04,
        sum(if (zhuanzhang_amount=0,0,1)) over w  zhuanzhang_05,
        sum(zhuanzhang_amount) over w zhuanzhang_06,
        0.5                     zhuanzhang_07,
        1                       zhuanzhang_08,
        1                       zhuanzhang_09,
        -- 存取相关
        sum(if (cunqu_amount=0,0,1)) over w cunqu_01,
        sum(cunqu_amount) over w cunqu_02,
        max (cunqu_amount) over w cunqu_03,
        if(max (cunqu_amount) over w =0,0,1) cunqu_04,
        sum(if (cunqu_amount=0,0,1)) over w  cunqu_05,
        sum(cunqu_amount) over w cunqu_06,
        0.5                     cunqu_07,
        1                       cunqu_08,
        1                       cunqu_09,
        -- 其他相关
        sum(if (other_amount=0,0,1)) over w other_01,
        sum(other_amount) over w other_02,
        max (other_amount) over w other_03,
        if(max (other_amount) over w =0,0,1)  other_04,
        sum(if (other_amount=0,0,1)) over w  other_05,
        sum(other_amount) over w other_06,
        0.5                     other_07,
        1                       other_08,
        1                       other_09
from every_type_info_table
WINDOW w AS (order by et RANGE BETWEEN INTERVAL '1' minute preceding AND CURRENT ROW);

-- todo 创建3天的信息视图
create view mid_data_table_threeday as
select
        et,
-- 消费相关
        sum(if (xiaofei_amount=0,0,1)) over w xiaofei_10,
        sum(xiaofei_amount) over w xiaofei_11,
        max (xiaofei_amount) over w xiaofei_12,
        count(distinct xiaofei_txn_dt) over w xiaofei_13,
        sum(if (xiaofei_amount=0,0,1))over w /3    xiaofei_14,
        sum(xiaofei_amount)over w /3   xiaofei_15,
        0.5                     xiaofei_16,
        3 xiaofei_17,
        3 xiaofei_18,
        if(count(distinct  xiaofei_txn_dt) over w =3,'是','否') xiaofei_19,
        sum(xiaofei_amount) over w >50000  xiaofei_20,
        sum(xiaofei_amount) over w >100000 xiaofei_21,
        sum(xiaofei_amount) over w >250000 xiaofei_22,
        sum(xiaofei_amount) over w >500000 xiaofei_23,
-- 办公相关
        sum(if (bangong_amount=0,0,1)) over w bangong_10,
        sum(bangong_amount) over w bangong_11,
        max (bangong_amount) over w bangong_12,
        count(distinct  bangong_txn_dt) over w bangong_13,
        sum(if (bangong_amount=0,0,1))over w /3   bangong_14,
        sum(bangong_amount)over w /3   bangong_15,
        0.5                     bangong_16,
        3 bangong_17,
        3 bangong_18,
        if(count(distinct  bangong_txn_dt) over w =3,'是','否') bangong_19,
        sum(bangong_amount) over w >50000  bangong_20,
        sum(bangong_amount) over w >100000 bangong_21,
        sum(bangong_amount) over w >250000 bangong_22,
        sum(bangong_amount) over w >500000 bangong_23,
--薪资相关
		sum(if (xinzi_amount=0,0,1)) over w xinzi_10,
        sum(xinzi_amount) over w xinzi_11,
        max (xinzi_amount) over w xinzi_12,
        count(distinct  xinzi_txn_dt) over w xinzi_13,
        sum(if (xinzi_amount=0,0,1))over w /3   xinzi_14,
        sum(xinzi_amount)over w /3  xinzi_15,
        0.5                     xinzi_16,
        3 xinzi_17,
        3 xinzi_18,
        if(count(distinct  xinzi_txn_dt) over w =3,'是','否') xinzi_19,
        sum(xinzi_amount) over w >50000  xinzi_20,
        sum(xinzi_amount) over w >100000 xinzi_21,
        sum(xinzi_amount) over w >250000 xinzi_22,
        sum(xinzi_amount) over w >500000 xinzi_23,
--保险相关
        sum(if (baoxian_amount=0,0,1)) over w baoxian_10,
        sum(baoxian_amount) over w baoxian_11,
        max (baoxian_amount) over w baoxian_12,
        count(distinct  baoxian_txn_dt) over w baoxian_13,
        sum(if (baoxian_amount=0,0,1))over w /3  baoxian_14,
        sum(baoxian_amount)over w /3  baoxian_15,
        0.5                     baoxian_16,
        3 baoxian_17,
        3 baoxian_18,
        if(count(distinct  baoxian_txn_dt) over w =3,'是','否') baoxian_19,
        sum(baoxian_amount) over w >50000  baoxian_20,
        sum(baoxian_amount) over w >100000 baoxian_21,
        sum(baoxian_amount) over w >250000 baoxian_22,
        sum(baoxian_amount) over w >500000 baoxian_23,
--投资相关
        sum(if (touzi_amount=0,0,1)) over w touzi_10,
        sum(touzi_amount) over w touzi_11,
        max (touzi_amount) over w touzi_12,
        count(distinct  touzi_txn_dt) over w touzi_13,
        sum(if (touzi_amount=0,0,1))over w /3   touzi_14,
        sum(touzi_amount)over w /3 touzi_15,
        0.5                     touzi_16,
        3 touzi_17,
        3 touzi_18,
        if(count(distinct  touzi_txn_dt) over w =3,'是','否') touzi_19,
        sum(touzi_amount) over w >50000  touzi_20,
        sum(touzi_amount) over w >100000 touzi_21,
        sum(touzi_amount) over w >250000 touzi_22,
        sum(touzi_amount) over w >500000 touzi_23,
--融资相关
        sum(if (rongzi_amount=0,0,1)) over w rongzi_10,
        sum(rongzi_amount) over w rongzi_11,
        max (rongzi_amount) over w rongzi_12,
        count(distinct  rongzi_txn_dt) over w rongzi_13,
        sum(if (rongzi_amount=0,0,1))over w /3    rongzi_14,
        sum(rongzi_amount)over w /3   rongzi_15,
        0.5                     rongzi_16,
        3 rongzi_17,
        3 rongzi_18,
        if(count(distinct  rongzi_txn_dt) over w =3,'是','否') rongzi_19,
        sum(rongzi_amount) over w >50000  rongzi_20,
        sum(rongzi_amount) over w >100000 rongzi_21,
        sum(rongzi_amount) over w >250000 rongzi_22,
        sum(rongzi_amount) over w >500000 rongzi_23,
-- 转账相关
        sum(if (zhuanzhang_amount=0,0,1)) over w zhuanzhang_10,
        sum(zhuanzhang_amount) over w zhuanzhang_11,
        max (zhuanzhang_amount) over w zhuanzhang_12,
        count(distinct  zhuanzhang_txn_dt) over w zhuanzhang_13,
        sum(if (zhuanzhang_amount=0,0,1))over w /3    zhuanzhang_14,
        sum(zhuanzhang_amount)over w /3   zhuanzhang_15,
        0.5                     zhuanzhang_16,
        3 zhuanzhang_17,
        3 zhuanzhang_18,
        if(count(distinct  zhuanzhang_txn_dt) over w =3,'是','否') zhuanzhang_19,
        sum(zhuanzhang_amount) over w >50000  zhuanzhang_20,
        sum(zhuanzhang_amount) over w >100000 zhuanzhang_21,
        sum(zhuanzhang_amount) over w >250000 zhuanzhang_22,
        sum(zhuanzhang_amount) over w >500000 zhuanzhang_23,
-- 存取相关
        sum(if (cunqu_amount=0,0,1)) over w cunqu_10,
        sum(cunqu_amount) over w cunqu_11,
        max (cunqu_amount) over w cunqu_12,
        count(distinct  cunqu_txn_dt) over w cunqu_13,
        sum(if (cunqu_amount=0,0,1))over w /3    cunqu_14,
        sum(cunqu_amount)over w /3   cunqu_15,
        0.5                     cunqu_16,
        3 cunqu_17,
        3 cunqu_18,
        if(count(distinct  cunqu_txn_dt) over w =3,'是','否') cunqu_19,
        sum(cunqu_amount) over w >50000  cunqu_20,
        sum(cunqu_amount) over w >100000 cunqu_21,
        sum(cunqu_amount) over w >250000 cunqu_22,
        sum(cunqu_amount) over w >500000 cunqu_23,
-- 其他相关
        sum(if (other_amount=0,0,1)) over w other_10,
        sum(other_amount) over w other_11,
        max (other_amount) over w other_12,
        count(distinct  other_txn_dt) over w other_13,
        sum(if (other_amount=0,0,1))over w /3    other_14,
        sum(other_amount)over w /3   other_15,
        0.5                     other_16,
        3 other_17,
        3 other_18,
        if(count(distinct  other_txn_dt) over w =3,'是','否') other_19,
        sum(other_amount) over w >50000  other_20,
        sum(other_amount) over w >100000 other_21,
        sum(other_amount) over w >250000 other_22,
        sum(other_amount) over w >500000 other_23
from every_type_info_table
WINDOW w AS (order by et RANGE BETWEEN INTERVAL '3' minute preceding AND CURRENT ROW);


--todo 整合 1天和 3天的数据
insert into sink_table_1
select
        xiaofei_01 as xiaofei_01,
        cast(xiaofei_02 as decimal(10,0)) as xiaofei_02,
        cast(xiaofei_03 as decimal(10,0)) as xiaofei_03,
        xiaofei_04 as xiaofei_04,
        xiaofei_05 as xiaofei_05,
        cast(xiaofei_06 as decimal(10,0)) as xiaofei_06,
        cast(xiaofei_07 as float) as xiaofei_07,
        cast(xiaofei_08 as float) as xiaofei_08,
        cast(xiaofei_09 as float) as xiaofei_09,
        xiaofei_10 as xiaofei_10,
        cast(xiaofei_11 as DECIMAL(18, 2)) as xiaofei_11,
        cast(xiaofei_12 as DECIMAL(18, 2)) as xiaofei_12,
        xiaofei_13 as xiaofei_13,
        xiaofei_14 as xiaofei_14,
        cast(xiaofei_15 as DECIMAL(18, 2)) as xiaofei_15,
        cast(xiaofei_16 as float) as xiaofei_16,
        cast(xiaofei_17 as float) as xiaofei_17,
        cast(xiaofei_18 as float) as xiaofei_18,
        xiaofei_19 as xiaofei_19,
        if(xiaofei_20,'是','否') as xiaofei_20,
        if(xiaofei_21,'是','否') as xiaofei_21,
        if(xiaofei_22,'是','否') as xiaofei_22,
        if(xiaofei_23,'是','否') as xiaofei_23,
        bangong_01 as bangong_01,
        cast(bangong_02 as decimal(10,0)) as bangong_02,
        cast(bangong_03 as decimal(10,0)) as bangong_03,
        bangong_04 as bangong_04,
        bangong_05 as bangong_05,
        cast(bangong_06 as decimal(10,0)) as bangong_06,
        cast(bangong_07 as float) as bangong_07,
        cast(bangong_08 as float) as bangong_08,
        cast(bangong_09 as float) as bangong_09,
        bangong_10 as bangong_10,
        cast(bangong_11 as DECIMAL(18, 2)) as bangong_11,
        cast(bangong_12 as DECIMAL(18, 2)) as bangong_12,
        bangong_13 as bangong_13,
        bangong_14 as bangong_14,
        cast(bangong_15 as DECIMAL(18, 2)) as bangong_15,
        cast(bangong_16 as float) as bangong_16,
        cast(bangong_17 as float) as bangong_17,
        cast(bangong_18 as float) as bangong_18,
        bangong_19 as bangong_19,
        if(bangong_20,'是','否') as bangong_20,
        if(bangong_21,'是','否') as bangong_21,
        if(bangong_22,'是','否') as bangong_22,
        if(bangong_23,'是','否') as bangong_23,
        xinzi_01 as xinzi_01,
        cast(xinzi_02 as decimal(10,0)) as xinzi_02,
        cast(xinzi_03 as decimal(10,0)) as xinzi_03,
        xinzi_04 as xinzi_04,
        xinzi_05 as xinzi_05,
        cast(xinzi_06 as decimal(10,0)) as xinzi_06,
        cast(xinzi_07 as float) as xinzi_07,
        cast(xinzi_08 as float) as xinzi_08,
        cast(xinzi_09 as float) as xinzi_09,
        xinzi_10 as xinzi_10,
        cast(xinzi_11 as DECIMAL(18, 2)) as xinzi_11,
        cast(xinzi_12 as DECIMAL(18, 2)) as xinzi_12,
        xinzi_13 as xinzi_13,
        xinzi_14 as xinzi_14,
        cast(xinzi_15 as DECIMAL(18, 2)) as xinzi_15,
        cast(xinzi_16 as float) as xinzi_16,
        cast(xinzi_17 as float) as xinzi_17,
        cast(xinzi_18 as float) as xinzi_18,
        xinzi_19 as xinzi_19,
        if(xinzi_20,'是','否') as xinzi_20,
        if(xinzi_21,'是','否') as xinzi_21,
        if(xinzi_22,'是','否') as xinzi_22,
        if(xinzi_23,'是','否') as xinzi_23,
        baoxian_01 as baoxian_01,
        cast(baoxian_02 as decimal(10,0)) as baoxian_02,
        cast(baoxian_03 as decimal(10,0)) as baoxian_03,
        baoxian_04 as baoxian_04,
        baoxian_05 as baoxian_05,
        cast(baoxian_06 as decimal(10,0)) as baoxian_06,
        cast(baoxian_07 as float) as baoxian_07,
        cast(baoxian_08 as float) as baoxian_08,
        cast(baoxian_09 as float) as baoxian_09,
        baoxian_10 as baoxian_10,
        cast(baoxian_11 as DECIMAL(18, 2)) as baoxian_11,
        cast(baoxian_12 as DECIMAL(18, 2)) as baoxian_12,
        baoxian_13 as baoxian_13,
        baoxian_14 as baoxian_14,
        cast(baoxian_15 as DECIMAL(18, 2)) as baoxian_15,
        cast(baoxian_16 as float) as baoxian_16,
        cast(baoxian_17 as float) as baoxian_17,
        cast(baoxian_18 as float) as baoxian_18,
        baoxian_19 as baoxian_19,
        if(baoxian_20,'是','否') as baoxian_20,
        if(baoxian_21,'是','否') as baoxian_21,
        if(baoxian_22,'是','否') as baoxian_22,
        if(baoxian_23,'是','否') as baoxian_23,
        touzi_01 as touzi_01,
        cast(touzi_02 as decimal(10,0)) as touzi_02,
        cast(touzi_03 as decimal(10,0)) as touzi_03,
        touzi_04 as touzi_04,
        touzi_05 as touzi_05,
        cast(touzi_06 as decimal(10,0)) as touzi_06,
        cast(touzi_07 as float) as touzi_07,
        cast(touzi_08 as float) as touzi_08,
        cast(touzi_09 as float) as touzi_09,
        touzi_10 as touzi_10,
        cast(touzi_11 as DECIMAL(18, 2)) as touzi_11,
        cast(touzi_12 as DECIMAL(18, 2)) as touzi_12,
        touzi_13 as touzi_13,
        touzi_14 as touzi_14,
        cast(touzi_15 as DECIMAL(18, 2)) as touzi_15,
        cast(touzi_16 as float) as touzi_16,
        cast(touzi_17 as float) as touzi_17,
        cast(touzi_18 as float) as touzi_18,
        touzi_19 as touzi_19,
        if(touzi_20,'是','否') as touzi_20,
        if(touzi_21,'是','否') as touzi_21,
        if(touzi_22,'是','否') as touzi_22,
        if(touzi_23,'是','否') as touzi_23,
        rongzi_01 as rongzi_01,
        cast(rongzi_02 as decimal(10,0)) as rongzi_02,
        cast(rongzi_03 as decimal(10,0)) as rongzi_03,
        rongzi_04 as rongzi_04,
        rongzi_05 as rongzi_05,
        cast(rongzi_06 as decimal(10,0)) as rongzi_06,
        cast(rongzi_07 as float) as rongzi_07,
        cast(rongzi_08 as float) as rongzi_08,
        cast(rongzi_09 as float) as rongzi_09,
        rongzi_10 as rongzi_10,
        cast(rongzi_11 as DECIMAL(18, 2)) as rongzi_11,
        cast(rongzi_12 as DECIMAL(18, 2)) as rongzi_12,
        rongzi_13 as rongzi_13,
        rongzi_14 as rongzi_14,
        cast(rongzi_15 as DECIMAL(18, 2)) as rongzi_15,
        cast(rongzi_16 as float) as rongzi_16,
        cast(rongzi_17 as float) as rongzi_17,
        cast(rongzi_18 as float) as rongzi_18,
        rongzi_19 as rongzi_19,
        if(rongzi_20,'是','否') as rongzi_20,
        if(rongzi_21,'是','否') as rongzi_21,
        if(rongzi_22,'是','否') as rongzi_22,
        if(rongzi_23,'是','否') as rongzi_23,
        zhuanzhang_01 as zhuanzhang_01,
        cast(zhuanzhang_02 as decimal(10,0)) as zhuanzhang_02,
        cast(zhuanzhang_03 as decimal(10,0)) as zhuanzhang_03,
        zhuanzhang_04 as zhuanzhang_04,
        zhuanzhang_05 as zhuanzhang_05,
        cast(zhuanzhang_06 as decimal(10,0)) as zhuanzhang_06,
        cast(zhuanzhang_07 as float) as zhuanzhang_07,
        cast(zhuanzhang_08 as float) as zhuanzhang_08,
        cast(zhuanzhang_09 as float) as zhuanzhang_09,
        zhuanzhang_10 as zhuanzhang_10,
        cast(zhuanzhang_11 as DECIMAL(18, 2)) as zhuanzhang_11,
        cast(zhuanzhang_12 as DECIMAL(18, 2)) as zhuanzhang_12,
        zhuanzhang_13 as zhuanzhang_13,
        zhuanzhang_14 as zhuanzhang_14,
        cast(zhuanzhang_15 as DECIMAL(18, 2)) as zhuanzhang_15,
        cast(zhuanzhang_16 as float) as zhuanzhang_16,
        cast(zhuanzhang_17 as float) as zhuanzhang_17,
        cast(zhuanzhang_18 as float) as zhuanzhang_18,
        zhuanzhang_19 as zhuanzhang_19,
        if(zhuanzhang_20,'是','否') as zhuanzhang_20,
        if(zhuanzhang_21,'是','否') as zhuanzhang_21,
        if(zhuanzhang_22,'是','否') as zhuanzhang_22,
        if(zhuanzhang_23,'是','否') as zhuanzhang_23,
        cunqu_01 as cunqu_01,
        cast(cunqu_02 as decimal(10,0)) as cunqu_02,
        cast(cunqu_03 as decimal(10,0)) as cunqu_03,
        cunqu_04 as cunqu_04,
        cunqu_05 as cunqu_05,
        cast(cunqu_06 as decimal(10,0)) as cunqu_06,
        cast(cunqu_07 as float) as cunqu_07,
        cast(cunqu_08 as float) as cunqu_08,
        cast(cunqu_09 as float) as cunqu_09,
        cunqu_10 as cunqu_10,
        cast(cunqu_11 as DECIMAL(18, 2)) as cunqu_11,
        cast(cunqu_12 as DECIMAL(18, 2)) as cunqu_12,
        cunqu_13 as cunqu_13,
        cunqu_14 as cunqu_14,
        cast(cunqu_15 as DECIMAL(18, 2)) as cunqu_15,
        cast(cunqu_16 as float) as cunqu_16,
        cast(cunqu_17 as float) as cunqu_17,
        cast(cunqu_18 as float) as cunqu_18,
        cunqu_19 as cunqu_19,
        if(cunqu_20,'是','否') as cunqu_20,
        if(cunqu_21,'是','否') as cunqu_21,
        if(cunqu_22,'是','否') as cunqu_22,
        if(cunqu_23,'是','否') as cunqu_23,
        other_01 as other_01,
        cast(other_02 as decimal(10,0)) as other_02,
        cast(other_03 as decimal(10,0)) as other_03,
        other_04 as other_04,
        other_05 as other_05,
        cast(other_06 as decimal(10,0)) as other_06,
        cast(other_07 as float) as other_07,
        cast(other_08 as float) as other_08,
        cast(other_09 as float) as other_09,
        other_10 as other_10,
        cast(other_11 as DECIMAL(18, 2)) as other_11,
        cast(other_12 as DECIMAL(18, 2)) as other_12,
        other_13 as other_13,
        other_14 as other_14,
        cast(other_15 as DECIMAL(18, 2)) as other_15,
        cast(other_16 as float) as other_16,
        cast(other_17 as float) as other_17,
        cast(other_18 as float) as other_18,
        other_19 as other_19,
        if(other_20,'是','否') as other_20,
        if(other_21,'是','否') as other_21,
        if(other_22,'是','否') as other_22,
        if(other_23,'是','否') as other_23
from mid_data_table_oneday,mid_data_table_threeday
where mid_data_table_threeday.et=mid_data_table_oneday.et
and mid_data_table_oneday.et BETWEEN mid_data_table_threeday.et - INTERVAL '2' second AND mid_data_table_threeday.et + INTERVAL '2' second;


