package com.otis.work.date20200925解析json;

import org.apache.flink.table.api.TableSchema;

import static org.apache.flink.table.api.DataTypes.*;

public class sql_schema {


//    public static TableSchema schema2= TableSchema.builder()
//            .field("PRH", new Object(FIELD("name",STRING())))
//                    .build();

    public static TableSchema schema1= TableSchema.builder()
            .field("filiations",ARRAY(
                    ROW(
                            FIELD("brnregorg",STRING()),
                            FIELD("brregno",STRING()),
                            FIELD("brncreditcode",STRING()),
                            FIELD("brname",STRING()))))
            .build();

    public static TableSchema schema =
            TableSchema.builder()
                    .field("yearReportForInvs",ARRAY(STRING()))
                    .field("filiations",ARRAY(
                            ROW(
                                    FIELD("brnregorg",STRING()),
                                    FIELD("brregno",STRING()),
                                    FIELD("brncreditcode",STRING()),
                                    FIELD("brname",STRING()))))
                    .field("yearReportAlterStocks",ARRAY(STRING()))
                    .field("yearReportSocSecs",ARRAY(
                            ROW(
                                    FIELD("unpaidsocialinsso110",STRING()),
                                    FIELD("unpaidsocialinsso210",STRING()),
                                    FIELD("unpaidsocialinsso310",STRING()),
                                    FIELD("unpaidsocialinsso410",STRING()),
                                    FIELD("unpaidsocialinsso510",STRING()),
                                    FIELD("totalwagesso110",STRING()),
                                    FIELD("totalwagesso310",STRING()),
                                    FIELD("totalwagesso210",STRING()),
                                    FIELD("so410",STRING()),
                                    FIELD("so310",STRING()),
                                    FIELD("so210",STRING()),
                                    FIELD("so110",STRING()),
                                    FIELD("totalwagesso510",STRING()),
                                    FIELD("totalwagesso410",STRING()),
                                    FIELD("totalpaymentso210",STRING()),
                                    FIELD("totalpaymentso310",STRING()),
                                    FIELD("totalpaymentso110",STRING()),
                                    FIELD("totalpaymentso410",STRING()),
                                    FIELD("totalpaymentso510",STRING()),
                                    FIELD("ancheid",STRING()),
                                    FIELD("so510",STRING()))))
                    .field("punisheds",ARRAY(
                            ROW(
                                    FIELD("regdateclean",STRING()),
                                    FIELD("courtname",STRING()),
                                    FIELD("ysfzd",STRING()),
                                    FIELD("execmoney",STRING()),
                                    FIELD("inameclean",STRING()),
                                    FIELD("type",STRING()),
                                    FIELD("casecode",STRING()),
                                    FIELD("sexyclean",STRING()),
                                    FIELD("casestate",STRING()),
                                    FIELD("ageclean",STRING()),
                                    FIELD("cardnumclean",STRING()),
                                    FIELD("focusnumber",STRING()),
                                    FIELD("areanameclean",STRING()))))
                    .field("yearReportWebSiteInfos",ARRAY(
                            ROW(
                                    FIELD("websitname",STRING()),
                                    FIELD("webtype",STRING()),
                                    FIELD("domain",STRING()),
                                    FIELD("ancheid",STRING()))))
                    .field("yearReportSubCapitals",ARRAY(
                            ROW(
                                    FIELD("inv",STRING()),
                                    FIELD("lisubconam",STRING()),//金额类
                                    FIELD("conform",STRING()),
                                    FIELD("currency",STRING()),
                                    FIELD("ancheid",STRING()),
                                    FIELD("condate",STRING()))))
                    .field("frpositions",ARRAY(
                            ROW(
                                    FIELD("esdate",STRING()),
                                    FIELD("regno",STRING()),
                                    FIELD("ppvamount",STRING()),
                                    FIELD("enttype",STRING()),
                                    FIELD("regcapcur",STRING()),
                                    FIELD("candate",STRING()),
                                    FIELD("lerepsign",STRING()),
                                    FIELD("entname",STRING()),
                                    FIELD("regcap",STRING()),//金额类
                                    FIELD("name",STRING()),
                                    FIELD("regorg",STRING()),
                                    FIELD("position",STRING()),
                                    FIELD("entstatus",STRING()),
                                    FIELD("revdate",STRING()),
                                    FIELD("regorgcode",STRING()))))
                    .field("mortgagebasics",ARRAY(STRING()))
                    .field("mortgagepers",ARRAY(STRING()))
                    .field("yearReportAlters",ARRAY(STRING()))
                    .field("liquidations",ARRAY(STRING()))
                    .field("stockpawns",ARRAY(
                            ROW(
                                    FIELD("stkpawnregno",STRING()),
                                    FIELD("stkpawnczamt",STRING()),//金额类
                                    FIELD("stkpawnczcerno",STRING()),
                                    FIELD("stkpawnzqcerno",STRING()),
                                    FIELD("stkpawndate",STRING()),
                                    FIELD("stkpawnstatus",STRING()),
                                    FIELD("stkpawnczper",STRING()),
                                    FIELD("stkpawnregdate",STRING()),
                                    FIELD("stkpawnzqper",STRING()),
                                    FIELD("url",STRING()))))
                    .field("mortgagedebts",ARRAY(STRING()))
                    .field("mortgagepawns",ARRAY(STRING()))
                    .field("entcasebaseinfos",ARRAY(
                            ROW(
                                    FIELD("illegacttype",STRING()),
                                    FIELD("pendecno",STRING()),
                                    FIELD("pencontent",STRING()),
                                    FIELD("pentypecn",STRING()),
                                    FIELD("pentype",STRING()),
                                    FIELD("publicdate",STRING()),
                                    FIELD("penauthcn",STRING()),
                                    FIELD("penauth",STRING()),
                                    FIELD("pendecissdate",STRING()))))
                    .field("entinvs",ARRAY(
                            ROW(
                                    FIELD("esdate",STRING()),
                                    FIELD("regno",STRING()),
                                    FIELD("creditcode",STRING()),
                                    FIELD("enttype",STRING()),
                                    FIELD("entjgname",STRING()),
                                    FIELD("binvvamount",STRING()),
                                    FIELD("subconam",STRING()),//金额类
                                    FIELD("regcapcur",STRING()),
                                    FIELD("candate",STRING()),
                                    FIELD("conform",STRING()),
                                    FIELD("regcap",STRING()),//金额类
                                    FIELD("name",STRING()),
                                    FIELD("regorg",STRING()),
                                    FIELD("congrocur",STRING()),
                                    FIELD("entstatus",STRING()),
                                    FIELD("fundedratio",STRING()),
                                    FIELD("revdate",STRING()),
                                    FIELD("regorgcode",STRING()))))
                    .field("punishbreaks",ARRAY(STRING()))
                    .field("stockpawnrevs",ARRAY(
                            ROW(
                                    FIELD("stkpawnres",STRING()),
                                    FIELD("stkpawndate",STRING()),
                                    FIELD("url",STRING()))))
                    .field("yearReportForGuarantees",ARRAY(STRING()))
                    .field("stockpawnalts",ARRAY(STRING()))
                    .field("mortgageregs",ARRAY(STRING()))
                    .field("mortgagealts",ARRAY(STRING()))
                    .field("yearReportPaidUpCapitals",ARRAY(
                            ROW(
                                    FIELD("inv",STRING()),
                                    FIELD("liacconam",STRING()),//金额类
                                    FIELD("conform",STRING()),
                                    FIELD("currency",STRING()),
                                    FIELD("ancheid",STRING()),
                                    FIELD("condate",STRING()))))
                    .field("relatedpunishbreaks",ARRAY(
                            ROW(
                                    FIELD("businessentity",STRING()),
                                    FIELD("regdateclean",STRING()),
                                    FIELD("courtname",STRING()),
                                    FIELD("ysfzd",STRING()),
                                    FIELD("inameclean",STRING()),
                                    FIELD("exitdate",STRING()),
                                    FIELD("type",STRING()),
                                    FIELD("disrupttypename",STRING()),
                                    FIELD("casecode",STRING()),
                                    FIELD("cardnum",STRING()),
                                    FIELD("performance",STRING()),
                                    FIELD("sexyclean",STRING()),
                                    FIELD("casestate",STRING()),
                                    FIELD("ageclean",STRING()),
                                    FIELD("duty",STRING()),
                                    FIELD("gistunit",STRING()),
                                    FIELD("publishdateclean",STRING()),
                                    FIELD("unperformpart",STRING()),
                                    FIELD("focusnumber",STRING()),
                                    FIELD("areanameclean",STRING()),
                                    FIELD("gistid",STRING()),
                                    FIELD("performedpart",STRING()))))
                    .field("shareholders",ARRAY(
                            ROW(
                                    FIELD("country",STRING()),
                                    FIELD("invtype",STRING()),
                                    FIELD("conform",STRING()),
                                    FIELD("shaname",STRING()),
                                    FIELD("fundedratio",STRING()),
                                    FIELD("subconam",STRING()),//金额类
                                    FIELD("condate",STRING()),
                                    FIELD("regcapcur",STRING()))))
                    .field("mortgagecans",ARRAY(STRING()))
                    .field("frinvs",ARRAY(
                            ROW(
                                    FIELD("esdate",STRING()),
                                    FIELD("regno",STRING()),
                                    FIELD("creditcode",STRING()),
                                    FIELD("enttype",STRING()),
                                    FIELD("subconam",STRING()),//金额类
                                    FIELD("regcapcur",STRING()),
                                    FIELD("candate",STRING()),
                                    FIELD("pinvamount",STRING()),
                                    FIELD("conform",STRING()),
                                    FIELD("entname",STRING()),
                                    FIELD("regcap",STRING()),//金额类
                                    FIELD("name",STRING()),
                                    FIELD("regorg",STRING()),
                                    FIELD("currency",STRING()),
                                    FIELD("entstatus",STRING()),
                                    FIELD("fundedratio",STRING()),
                                    FIELD("revdate",STRING()),
                                    FIELD("regorgcode",STRING()))))
                    .field("relatedpunisheds",ARRAY(
                            ROW(
                                    FIELD("regdateclean",STRING()),
                                    FIELD("courtname",STRING()),
                                    FIELD("ysfzd",STRING()),
                                    FIELD("execmoney",STRING()),
                                    FIELD("inameclean",STRING()),
                                    FIELD("type",STRING()),
                                    FIELD("casecode",STRING()),
                                    FIELD("sexyclean",STRING()),
                                    FIELD("casestate",STRING()),
                                    FIELD("ageclean",STRING()),
                                    FIELD("cardnumclean",STRING()),
                                    FIELD("focusnumber",STRING()),
                                    FIELD("areanameclean",STRING()))))
                    .field("sharesfrosts",ARRAY(STRING()))
                    .field("exceptions",ARRAY(STRING()))
                    .field("yearReportBasics",ARRAY(
                            ROW(
                                    FIELD("regno",STRING()),
                                    FIELD("entname",STRING()),
                                    FIELD("postalcode",STRING()),
                                    FIELD("ancheyear",STRING()),
                                    FIELD("busst",STRING()),
                                    FIELD("tel",STRING()),
                                    FIELD("ancheid",STRING()),
                                    FIELD("addr",STRING()),
                                    FIELD("creditno",STRING()),
                                    FIELD("email",STRING()),
                                    FIELD("anchedate",STRING()))))
                    .field("persons",ARRAY(
                            ROW(
                                    FIELD("personamount",STRING()),
                                    FIELD("pername",STRING()),
                                    FIELD("entname",STRING()),
                                    FIELD("isFr",STRING()),
                                    FIELD("position",STRING()))))
                    .field("alters",ARRAY(
                            ROW(
                                    FIELD("altbe",STRING()),
                                    FIELD("altaf",STRING()),
                                    FIELD("altitem",STRING()),
                                    FIELD("altdate",STRING()))))
                    .field("basic", ROW(
                                    FIELD("esdate",STRING()),
                                    FIELD("creditcode",STRING()),
                                    FIELD("dom",STRING()),
                                    FIELD("zsopscope",STRING()),
                                    FIELD("reccap",STRING()),//金额类
                                    FIELD("enttype",STRING()),
                                    FIELD("industryphyall",STRING()),
                                    FIELD("industryphyname",STRING()),
                                    FIELD("industryphycode",STRING()),
                                    FIELD("opfrom",STRING()),
                                    FIELD("enttypecode",STRING()),
                                    FIELD("regorgdistrict",STRING()),
                                    FIELD("industryconame",STRING()),
                                    FIELD("entname",STRING()),
                                    FIELD("regorg",STRING()),
                                    FIELD("domdistrict",STRING()),
                                    FIELD("tel",STRING()),
                                    FIELD("revdate",STRING()),
                                    FIELD("abuitem",STRING()),
                                    FIELD("email",STRING()),
                                    FIELD("frname",STRING()),
                                    FIELD("regno",STRING()),
                                    FIELD("entnameeng",STRING()),
                                    FIELD("oriregno",STRING()),
                                    FIELD("ancheyear",STRING()),
                                    FIELD("opto",STRING()),
                                    FIELD("regcapcur",STRING()),
                                    FIELD("empnum",STRING()),
                                    FIELD("industrycoall",STRING()),
                                    FIELD("candate",STRING()),
                                    FIELD("industrycocode",STRING()),
                                    FIELD("regcap",STRING()),//金额类
                                    FIELD("regorgcity",STRING()),
                                    FIELD("regorgprovince",STRING()),
                                    FIELD("entstatus",STRING()),
                                    FIELD("entnameold",STRING()),
                                    FIELD("regorgcode",STRING()),
                                    FIELD("apprdate",STRING())))
                    .build();
}
